### PR TITLE
Fix console errors on some PR pages

### LINKED ISSUE #3932: `onPrMergePanelOpen()` may be broken
1. Go to a PR page (e.g. https://github.com/sindresorhus/refined-github/pull/3886)
2. Type something in the comment form at the bottom
3. Reload the page

Two features will produce an error (sometimes only one of them appear):
```text
clear-pr-merge-commit-message → TypeError: messageField is undefined
suggest-commit-title-limit → TypeError: inputField is undefined
```

Since both of these features make use of `onPrMergePanelOpen`, I'm guessing that's where the problem is.

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #3932 

## Test URLs
1. Type something in the comment box at the bottom (without sending it)
2. Soft-reload the page
3. `clear-pr-merge-commit-message` and `suggest-commit-title-limit` should NOT produce errors in the console

Tested in Firefox & Chromium.

### CODE REVIEW

File: source/github-events/on-pr-merge-panel-open.ts [hunk 1]
```diff
@@ -10,7 +10,10 @@ const delegateHandler = mem((callback: EventListener) => (event: delegate.Event)
 
 const sessionResumeHandler = mem((callback: EventListener) => async (event: Event) => {
 	await Promise.resolve(); // The `session:resume` event fires a bit too early
-	callback(event);
+	// Avoid triggering the callback when a page with a non-empty comment field is reloaded #3932
+	if ((event as CustomEvent).detail.targetId !== 'new_comment_field') {
```
Comment (cheap-glitch) [inline source/github-events/on-pr-merge-panel-open.ts:14]: Not sure about the type coercion. Maybe the callback should be defined as taking a `CustomEvent` in the first place?

Comment (fregante) [reply source/github-events/on-pr-merge-panel-open.ts:14]: Yes if it works

Comment (cheap-glitch) [reply source/github-events/on-pr-merge-panel-open.ts:14]: It can work without any assertions if we declare `'session:resume'` as a `CustomElement`:
```typescript
declare global {
	interface DocumentEventMap {
		'session:resume': CustomEvent
	}
}
```

File: source/github-events/on-pr-merge-panel-open.ts [hunk 2]
```diff
@@ -8,9 +8,18 @@ const delegateHandler = mem((callback: EventListener) => (event: delegate.Event)
 	}
 });
 
-const sessionResumeHandler = mem((callback: EventListener) => async (event: Event) => {
+declare global {
+	interface DocumentEventMap {
+		'session:resume': CustomEvent;
```
Comment (fregante) [inline source/github-events/on-pr-merge-panel-open.ts:13]: global.d.ts has other events too, it should be there, not here

**Review by fregante — APPROVED** [review]

**Comment by fregante** [comment]
Thank you for looking into this!

There's also a related behavior that I finally put into an issue: https://github.com/sindresorhus/refined-github/issues/4101

**Comment by yakov116** [comment]
Looks like this broke `clear-pr-merge-commit-message` not sure why. Its very hard to test because once the field is updated GitHub saves what it was updated to.

I reverted this PR locally and then the feature started working correctly
