### PR TITLE
Abbreviate `bugs-tab`  and `releases-tab` count

### LINKED ISSUE #4107: Use 1k instead of 1000 in `bugs-tab`
The bugs count should format like the issues count.
e

### PR DESCRIPTION
**Pull request by yakov116**
Closes #4107 

## Test URLs
https://github.com/microsoft/vscode

## Screenshot
Before
image

After
image

Question should we replace `.0`?

Without the .0

image

### CODE REVIEW

**Review by fregante — APPROVED** [review]
Neat!

**Comment by yakov116** [comment]
> Question should we replace `.0`?

?

File: source/features/bugs-tab.tsx [hunk 1]
```diff
@@ -93,7 +93,11 @@ async function init(): Promise<void | false> {
 
 	// Update bugs count
 	try {
-		bugsCounter.textContent = abbreviateNumber(await countPromise);
+		bugsCounter.textContent = abbreviateNumber(await countPromise)
+			// 1.0K to 1k
+			.replace('.0K', 'k')
```
Comment (kidonng) [inline source/features/bugs-tab.tsx:98]: Maybe just `.replace(/(\.0)?K/, 'k')` but this is clearer so fine

**Comment by fregante** [comment]
https://github.com/moh3n9595/js-abbreviation-number#usage

**Comment by yakov116** [comment]
> moh3n9595/js-abbreviation-number#usage

I saw that

Using `abbreviateNumber(number, 0)` will round everything to the nearest 1000.

For example `abbreviateNumber(1500, 0) => 2K` that is not what we want.

**Comment by fregante** [comment]
Ew… we can either find an alternative (micro) module or import it, adjust it, re-export it from a file under the helpers, so the same can be used in the other feature that uses `js-abbreviation-number`

**Comment by yakov116** [comment]
I will cleanup the lock later.

Should should I make a helper called `issueNumberFormat`?

File: source/features/bugs-tab.tsx [hunk 2]
```diff
@@ -93,7 +93,9 @@ async function init(): Promise<void | false> {
 
 	// Update bugs count
 	try {
-		bugsCounter.textContent = numberFormatter.format(await countPromise);
+		bugsCounter.textContent = abbreviateNumber(await countPromise, 1, {padding: false})
+			// Matches GitHub lowercase `k` style
+			.toLowerCase();
```
Comment (fregante) [inline source/features/bugs-tab.tsx:98]:
```suggestion
		bugsCounter.textContent = abbreviateNumber(await countPromise, 1, {
			padding: false,
			symbols: ['', 'k']
		});
```

Comment (fregante) [reply source/features/bugs-tab.tsx:98]: Nevermind

Comment (fregante) [reply source/features/bugs-tab.tsx:98]:
```suggestion
		bugsCounter.textContent = abbreviateNumber(await countPromise, 1, {padding: false}).toLowerCase();
```

Comment (yakov116) [reply source/features/bugs-tab.tsx:98]: DUHH I was fighting with the update for about 35 min before.......

Comment (fregante) [reply source/features/bugs-tab.tsx:98]: I can imagine 😅

File: webpack.config.ts [hunk 3]
```diff
@@ -116,7 +116,6 @@ const config: Configuration = {
 			),
 
 			__filebasename: webpack.DefinePlugin.runtimeValue(
-				// @ts-expect-error
```
Comment (fregante) [inline webpack.config.ts:119]: Let's keep unrelated package-lock changes for the next lint. I added some lines in #4111 because they are macOS-specific and always get added by `npm i`, just for macOS users :(

Comment (yakov116) [reply webpack.config.ts:119]: I am doing it now. I was just so mad I wanted to just commit and fix it up.

File: source/helpers/issue-number-format.ts [hunk 4]
```diff
@@ -0,0 +1,5 @@
+import {abbreviateNumber} from 'js-abbreviation-number';
+
+export default function issueNumberFormat(count: number): string {
+	return abbreviateNumber(count, 1, {padding: false}).toLowerCase();
```
Comment (fregante) [inline source/helpers/issue-number-format.ts:4]:
```suggestion
import {abbreviateNumber as abbreviateNumber_} from 'js-abbreviation-number';

export default function abbreviateNumber(count: number): string {
	return abbreviateNumber_(count, 1, {padding: false}).toLowerCase();
```

Comment (yakov116) [reply source/helpers/issue-number-format.ts:4]: rename file?

**Review by fregante — APPROVED** [review]
