### PR TITLE
Fix `quick-mention` on review events

### LINKED ISSUE #4844: `quick-mention`: undefined is not an object (evaluating 'select_dom("img", avatar).alt')
This console error consistently appears on the test page only. I don't see it anywhere else

## Console errors

```
init@safari-web-extension://1282C589-9FD0-4F34-9127-696B6A884350/build/refined-github.js:7765:56
@safari-web-extension://1282C589-9FD0-4F34-9127-696B6A884350/build/refined-github.js:1964:28
asyncFunctionResume@[native code]
@safari-web-extension://1282C589-9FD0-4F34-9127-696B6A884350/build/refined-github.js:1697:17
asyncFunctionResume@[native code]
forEach@[native code]
run@safari-web-extension://1282C589-9FD0-4F34-9127-696B6A884350/build/refined-github.js:1696:23
```
	

## Test URL

https://github.com/pixiebrix/pixiebrix-extension/pull/1548

## Browser

Safari

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #4844 

## Test URLs
https://github.com/pixiebrix/pixiebrix-extension/pull/1548

## Screenshot
https://user-images.githubusercontent.com/46634000/135748608-81ecd14e-681e-48c8-9b98-9ad89bed14e7.mp4

### CODE REVIEW

File: source/features/quick-mention.tsx [hunk 1]
```diff
@@ -6,10 +6,15 @@ import {ReplyIcon} from '@primer/octicons-react';
...
 import * as textFieldEdit from 'text-field-edit';
 
+import {wrap} from '../helpers/dom-utils';
 import features from '.';
 import {getUsername} from '../github-helpers';
 import onNewComments from '../github-events/on-new-comments';
 
+function prefixUserMention(userMention: string): string {
+	return userMention.startsWith('@') ? userMention : '@' + userMention;
+}
```
Comment (cheap-glitch) [inline source/features/quick-mention.tsx:16]: Needed because the `alt` attribute of avatars next to review events doesn't include the `@` (i.e. it's just `fregante` instead of `@fregante`).

Comment (fregante) [reply source/features/quick-mention.tsx:16]:
```suggestion
function prefixUserMention(userMention: string): string {
	return '@' + userMention.replace('@', ''); // The alt may or may not have it #4859
}
```

**Review by fregante — APPROVED** [review]
