### PR TITLE
Restore `raw-file-link` feature

### LINKED ISSUE #2006: `raw-file-link` broken in PRs due to new dropdown
1. Visit https://github.com/sindresorhus/refined-github/pull/1783/files
2. No "Raw" link because they moved everything in the dropdown:

Last PR: https://github.com/sindresorhus/refined-github/pull/1924
cc @idasbiste

### PR DESCRIPTION
**Pull request by gavinhenderson**
Closes #2006  

View raw screenshot

# Test

https://github.com/sindresorhus/refined-github/pull/1783/files

### CODE REVIEW

File: source/features/raw-file-link.tsx [hunk 1]
```diff
@@ -10,17 +10,16 @@ const createRawUrl = (href: string): string => {
 };
 
 function addRawButtons(): void {
-	for (const anchor of select.all<HTMLAnchorElement>('.file-header .file-actions > div.BtnGroup [href*=\'/blob/\']:last-child')) {
+	for (const anchor of select.all<HTMLAnchorElement>('.file-header .file-actions > div > details > details-menu > a:nth-child(3)')) {
```
Comment (bfred-it) [inline source/features/raw-file-link.tsx]: This selector seems overly specific, it should still look for `[href*=\'/blob/\']` instead

**Comment by gavinhenderson** [comment]
@bfred-it  Thanks for the feedback! I've made it less specific, using the href selector as suggested. Hopefully this makes it more robust to any future UI changes from upstream

File: source/features/raw-file-link.tsx [hunk 2]
```diff
@@ -10,17 +10,16 @@ const createRawUrl = (href: string): string => {
 };
 
 function addRawButtons(): void {
-	for (const anchor of select.all<HTMLAnchorElement>('.file-header .file-actions > div.BtnGroup [href*=\'/blob/\']:last-child')) {
+	for (const anchor of select.all<HTMLAnchorElement>('.file-header .file-actions > div > details [href*=\'/blob/\']')) {
```
Comment (notlmn) [inline source/features/raw-file-link.tsx]: This can be `.file .js-file-header-dropdown [href*=\'/blob/\']`. You can even drop the `.file` part at the start too.

File: source/features/raw-file-link.tsx [hunk 3]
```diff
@@ -10,17 +10,16 @@ const createRawUrl = (href: string): string => {
...
 		anchor.after(
-			<a href={createRawUrl(anchor.pathname)} className="btn btn-sm BtnGroup-item">
-				Raw
+			<a href={createRawUrl(anchor.pathname)} className="pl-5 dropdown-item btn-link">
```
Comment (notlmn) [inline source/features/raw-file-link.tsx]:
```suggestion
			<a href={createRawUrl(anchor.pathname)} className="pl-5 dropdown-item btn-link" role="menuitem">
```

File: source/features/raw-file-link.tsx (hunk 2 above)
Comment (gavinhenderson) [reply source/features/raw-file-link.tsx]: Hey @notlmn , what's the benefit of that selector over others?

Comment (bfred-it) [reply source/features/raw-file-link.tsx]: > what's the benefit of that selector over others?

The shorter and less specific the better. Many `>` will make it too dependent on small variations

Comment (bfred-it) [reply source/features/raw-file-link.tsx]: Also perhaps we should avoid that `/blob/` check because that would match any link in a `/blob/` repo or `/blob/` directory. Let's try something like `[data-ga-click^="View file"]`

File: source/features/raw-file-link.tsx [hunk 4]
```diff
@@ -10,17 +10,16 @@ const createRawUrl = (href: string): string => {
...
-				Raw
+			<a href={createRawUrl(anchor.pathname)} className="pl-5 dropdown-item btn-link" role="menuitem">
+				View raw
 			</a>
 		);
 	}
 }
 
 function init(): void {
-	addRawButtons();
```
Comment (bfred-it) [inline source/features/raw-file-link.tsx]: This needs to be there, or else it will only run if there are many files in a PR

**Comment by gavinhenderson** [comment]
@bfred-it I initially removed it as it was duplicating as you said. Latest commit restores the call before the PR is loaded and makes sure not to duplicate the link.

File: source/features/raw-file-link.tsx [hunk 5]
```diff
@@ -10,16 +10,22 @@ const createRawUrl = (href: string): string => {
...
 
 function addRawButtons(): void {
-	for (const anchor of select.all<HTMLAnchorElement>('.js-file-header-dropdown [data-ga-click^="View file"]')) {
-		anchor.after(
-			<a href={createRawUrl(anchor.pathname)} className="pl-5 dropdown-item btn-link" role="menuitem">
-				View raw
-			</a>
-		);
+	for (const dropdown of select.all<HTMLElement>('.js-file-header-dropdown')) {
+		const anchor: HTMLAnchorElement | null = select('[data-ga-click^="View file"]', dropdown);
```
Comment (bfred-it) [inline source/features/raw-file-link.tsx]: In this case you can add a `!` at the end instead of specifying `|null`, and can specify the expected type with `<...>`

```
const anchor = select<HTMLAnchorElement>('[data-ga-click^="View file"]', dropdown)!;
```

**Comment by bfred-it** [comment]
Thanks for the fix 🐛 , @gavinhenderson

**Comment by gavinhenderson** [comment]
@bfred-it Thanks for the help!
