### PR TITLE
Fix "Make it easy to delete forks"

### LINKED ISSUE #776: Make it easy to delete forks
You know the drill. You want to contribute, so you create a fork, do a simple change and create pull request. You repeat this few times and you have created tons of unused forks in your account which just make it harder to find your repos you actually care about. Can we do something about this? Make it easier to delete fork repos? Or maybe toggle to hide such repos?

### PR DESCRIPTION
**Pull request by tanmayrajani**
#### fixes #776 
---------------------
- Fixed outdated selector
- Removed delete fork icon to make it look consistent with "Delete branch" button right above it. It now looks like this:

delete-fork-link

### CODE REVIEW

File: src/content.js [hunk 1]
```diff
@@ -248,14 +248,13 @@ function addDeleteForkLink() {
...
 	if (postMergeDescription) {
-		const currentBranch = postMergeDescription.querySelector('.commit-ref.current-branch');
+		const currentBranch = postMergeDescription.querySelector('.commit-ref');
 		const forkPath = currentBranch ? currentBranch.title.split(':')[0] : null;
 
 		if (forkPath && forkPath !== repoUrl) {
 			postMergeDescription.append(
 				<p id="refined-github-delete-fork-link">
 					<a href={`/${forkPath}/settings`}>
-						{icons.fork()}
```
Comment (bfred-it) [inline src/content.js]: Can we keep the fork icon? If the problem was the missing space, you can add it with `{' '}`

File: src/content.js [hunk 2]
```diff
@@ -248,14 +248,13 @@ function addDeleteForkLink() {
 	const postMergeDescription = select('#partial-pull-merging .merge-branch-description');
 
 	if (postMergeDescription) {
-		const currentBranch = postMergeDescription.querySelector('.commit-ref.current-branch');
+		const currentBranch = postMergeDescription.querySelector('.commit-ref');
 		const forkPath = currentBranch ? currentBranch.title.split(':')[0] : null;
 
 		if (forkPath && forkPath !== repoUrl) {
 			postMergeDescription.append(
 				<p id="refined-github-delete-fork-link">
```
Comment (bfred-it) [inline src/content.js]: I think we can avoid this `p`, just use the `id` on the link and center it via CSS

File: src/content.js (hunk 1 above)
Comment (bfred-it) [reply src/content.js]: Hmm I guess the reason why you removed it is that GH also removed their icon:

**Comment by bfred-it** [comment]
Thanks!
