### PR TITLE
Fix `bugs-tab` on non-issue pages

### LINKED ISSUE #3897: `bugs-tab`: Cannot read property 'pathname' of undefined
https://github.com/sindresorhus/refined-github

Don't have time to debug this second

### PR DESCRIPTION
**Pull request by yakov116**
Thanks for contributing! 🍄

1. LINKED ISSUES:
   Fixes #3897 

2. TEST URLS:
   Any non issue page
https://github.com/sindresorhus/refined-github

3. SCREENSHOT:
   None

### CODE REVIEW

File: source/github-helpers/search-query.ts [hunk 1]
```diff
@@ -60,16 +60,20 @@ export default class SearchQuery {
 			return currentQuery;
 		}
 
+		if (!this.link?.pathname) {
```
Comment (fregante) [inline source/github-helpers/search-query.ts:63]:
```suggestion
		if (!this.link) {
```

**Review by fregante — APPROVED** [review]
