### PR TITLE
Various fixes for `global-discussion-list-filters` feature

### LINKED ISSUE #1919: Button links in global Pull requests / Issues pages are messed up
Links to reproduce: [Pull requests](https://github.com/pulls), [Issues](https://github.com/issues). Then click either the `Commented` or `Yours` button. 

You can see in the screenshot that the href attributes of the original buttons (`Created`, `Assigned`, `Mentioned` and `Review requests` in the Pull requests page) don't have a space (`+`) after the `archived:false` attribute.

image

This is what it loads if I press one of them:

image

And this is how it looks with the extension disabled:

image

I have version 19.4.7.1857 of the extension.

Great work on the project. Keep it up! :)

### PR DESCRIPTION
**Pull request by mcornella**
Fixes https://github.com/sindresorhus/refined-github/issues/1919

Links to reproduce: global [Pull Requests](https://github.com/pulls) or [Issues](https://github.com/issues), then click either the `Commented` or `Yours` button.

Things this PR fixes:

1. In the global Issues page, the proper parameter is put in the URL so the filter is correct (i.e. pull requests don't appear as well).

2. When in a `Commented` or `Yours` query, the added query parameter is removed correctly from the rest of the buttons URLs (`Created`, `Assigned`, `Mentioned` and `Review requests`). The previous behaviors removed one space too many leading to parameters joined together. Fixes #1919.

3. When the query parameters contained a malformed query, the `Commented` or `Yours` buttons don't light up. For example, if the query contains `commented:username-and-something-else`, the regex doesn't match now, as opposed to it matching previously and highlighting the `Commented` button.

4. In the global Pull Requests page, the `Commented` and `Yours` buttons also include in the query the parameter `is:pr`, as was done for `is:issue` (fix 1) in the Issues page.

These fixes are listed in the order of the commits.

cc @bfred-it

### CODE REVIEW

**Comment by mcornella** [comment]
There's also another issue in that in the 'Pull requests' page the type (`is:pr`) is not set in the Commented and Yours sections, so we end up seeing issues as well. I have a fix but it looks ugly, so I'm marking this as a WIP.

**Comment by bfred-it** [comment]
Looks good, except now the file is executable 😳 755

**Comment by mcornella** [comment]
> Looks good, except now the file is executable 😳 755

Something wrong with my WSL setup sorry.

**Comment by mcornella** [comment]
I've pushed the fix for https://github.com/sindresorhus/refined-github/pull/1926#issuecomment-482822229 as well. 

But my thinking is that a better solution would be constructing the links based on the q parameter value, i.e. just adding the query to the q parameter instead of setting a `defaultQuery`. So if something different was searched, just adding `commenter:username` or `user:username` to that search. But that would change the feature substantially.

**Comment by sindresorhus** [comment]
@mcornella Can you fix the merge conflict and rebase from master (we enabled [TS strict mode](https://github.com/sindresorhus/refined-github/commit/7b3b275ad9a1b1409c56310c0b8ab286bef1f75f)) and fix any issues?

**Comment by mcornella** [comment]
I rebased and fix a TypeScript error with the type of the `types` object but I haven't used TS before so I don't know if the fix is idiomatic or there's a better way.

File: source/features/global-discussion-list-filters.tsx [hunk 1]
```diff
@@ -5,19 +5,26 @@ import {getUsername} from '../libs/utils';
 
 function init() {
 	const defaultQuery = 'is:open archived:false ';
-	const type = location.pathname === '/issues' ? ' is:issues' : ''; // Without this, the Issues page also displays PRs
+
+	// Without this, the Issues page also displays PRs, and viceversa
+	const types: { [path: string]: string } = {
+		'/issues': 'is:issue ',
+		'/pulls': 'is:pr '
```
Comment (bfred-it) [inline source/features/global-discussion-list-filters.tsx]: I don’t think this is needed, `is:pr` is implied in `/pulls` according to GitHub. Did the previous version throw TS errors? I’d revert this change

Comment (mcornella) [reply source/features/global-discussion-list-filters.tsx]: That's actually not what I've experienced. I've captured a couple of screenshots with the extension without these changes:

here's the default screen at [github.com/pulls](https://github.com/pulls); notice the extra `is:pr` parameter in the search field:
Captura de pantalla de 2019-04-18 17-59-07

and here's the screen in the `Commented` section, without the `is:pr` parameter:
Captura de pantalla de 2019-04-18 17-59-39

I'm still in `/pulls` but the lack of `is:pr` makes it show both Issues and PRs.

Comment (mcornella) [reply source/features/global-discussion-list-filters.tsx]: With the commit checked out, I get the proper search results:
Captura de pantalla de 2019-04-18 18-07-27

Comment (bfred-it) [reply source/features/global-discussion-list-filters.tsx]: Indeed, that only seems to apply to `/user/repo/pulls` and not `/pulls`

e.g. no issues appear here: https://github.com/sindresorhus/refined-github/pulls?utf8=%E2%9C%93&q=

**Comment by bfred-it** [comment]
This is great! Bugfixes and reproduction steps. What's not to like? Thanks! 🍋

**Comment by mcornella** [comment]
Thanks!
