### PR TITLE
Fix `minimize-upload-bar` on new issue

### LINKED ISSUE #2234: Can I have a Attach Files button in the issue creation description form?
Can I have a Attach Files button in the issue creation description form?

### PR DESCRIPTION
**Pull request by jerone**
# Description
Can't use `:last-child` selector, because the last child inside the markdown-toolbar on the new issue page is an hidden element.

# Closes 
Fixes #2234.

# Test
1. https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md

### CODE REVIEW

**Comment by bfred-it** [comment]
The `collapsible-content-button` is there; use this

https://github.com/sindresorhus/refined-github/blob/11b8ab4ef75b824cbbd2ed2dd1e3a80f24070b46/source/features/collapsible-content-button.tsx#L31

File: source/features/minimize-upload-bar.tsx [hunk 1]
```diff
@@ -6,13 +6,13 @@ import features from '../libs/features';
...
-	for (const toolbarGroup of select.all('form:not(.rgh-minimize-upload-bar) markdown-toolbar > :last-child')) {
-		toolbarGroup.prepend(
+	for (const toolbarButton of select.all('md-ref')) {
+		toolbarButton.after(
 			<button type="button" className="toolbar-item tooltipped tooltipped-n rgh-upload-btn" aria-label="Attach files">
 				{icons.cloudUpload()}
 			</button>
 		);
-		toolbarGroup.closest('form')!.classList.add('rgh-minimize-upload-bar');
+		toolbarButton.closest('form')!.classList.add('rgh-minimize-upload-bar');
```
Comment (bfred-it) [inline source/features/minimize-upload-bar.tsx]: This class is no longer used. Is it necessary? Will the current code cause duplicates when new comments are loaded?

Comment (jerone) [reply source/features/minimize-upload-bar.tsx]: I couldn't get any duplicate buttons. That's why I removed the `form:not(.rgh-minimize-upload-bar)` selector above. 
But this class is still used and necessary in the attached stylesheet.

**Comment by bfred-it** [comment]
Test
