### PR TITLE
Fix `mark-merge-commits-in-list` commit hash selector

### LINKED ISSUE #4468: `tags-on-commits-list`: Cannot read property 'committedDate' of null
URL: https://github.com/pixiebrix/pixiebrix-extension/commits/main

```
TypeError: Cannot read property 'committedDate' of null
  at getTags (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:15040:55)
  at async init (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:15056:34)
  at async runFeature (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:8934:11)
  at async setupPageLoad (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:8952:5)
```
```
TypeError: Cannot read property 'parents' of null
  at filterMergeCommits (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:10176:16)
  at async init (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:10187:24)
  at async runFeature (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:8934:11)
  at async setupPageLoad (chrome-extension://pplhppbihehddgkdedhpbfpbbbefeihl/build/refined-github.js:8952:5)
```
	
It catches the PR url, instead of the hash

https://github.com/sindresorhus/refined-github/blob/bcc113e677b4f0d91471a97cb3a8aefae9cb95c7/source/features/mark-merge-commits-in-list.tsx#L36-L38

Needs to exclude issue links

### PR DESCRIPTION
**Pull request by yakov116**
Closes #4468 

## Test URLs
https://github.com/pixiebrix/pixiebrix-extension/commits/main
https://github.com/babel/babel/commits/master?after=ddd40bf5c7ad8565fc990f26142f85613958a329+104

##Screenshot 

image

### CODE REVIEW

File: source/features/mark-merge-commits-in-list.tsx [hunk 1]
```diff
@@ -34,7 +34,7 @@ const filterMergeCommits = async (commits: string[]): Promise<string[]> => {
 
 // eslint-disable-next-line import/prefer-default-export
 export function getCommitHash(commit: HTMLElement): string {
-	return commit.querySelector('a[href]')!.pathname.split('/').pop()!;
+	return commit.querySelector('a[href]:not(.js-issue-link)')!.pathname.split('/').pop()!;
```
Comment (fregante) [inline source/features/mark-merge-commits-in-list.tsx:37]: If there's an easier element to select, let's not go by exclusion with `not`

```suggestion
	return select('[aria-label="Copy the full SHA"]', commit)!.getAttribute('value');
```

File: source/features/mark-merge-commits-in-list.tsx [hunk 2]
```diff
@@ -34,7 +34,7 @@ const filterMergeCommits = async (commits: string[]): Promise<string[]> => {
 
 // eslint-disable-next-line import/prefer-default-export
 export function getCommitHash(commit: HTMLElement): string {
-	return commit.querySelector('a[href]')!.pathname.split('/').pop()!;
+	return select('[aria-label="Copy the full SHA"]', commit)!.getAttribute('value');
```
Comment (yakov116) [inline source/features/mark-merge-commits-in-list.tsx:37]:
```suggestion
	return select('[aria-label="Copy the full SHA"]', commit)!.getAttribute('value')!;
```
