### PR TITLE
Remove `copy-file` from rendered pages

### LINKED ISSUE #4451: `copy-file` doesn't work on SVG files
~~I thought I reported this already, but I can't find the issue.~~

1. Open https://github.com/sindresorhus/refined-github/blob/main/media/icon.svg
2. Click the "Copy" button
3. Nothing happens, there's no code visible, it should only appear when the raw code is visible

~~We should find other rendered filetypes and make sure they all work the same way so we don't play wackamole.~~

Related: https://github.com/sindresorhus/refined-github/issues/4244

### PR DESCRIPTION
**Pull request by roottool**
Closes #4451

## Overview

`table.highlight` is a selector that means the area of displayed code.
I removed two delegates. This is because `.rgh-md-source` is a selector that doesn't exist in this repository.

### Screenshot

image

### SVG

https://github.com/sindresorhus/refined-github/blob/main/media/icon.svg

### Markdown

https://github.com/sindresorhus/refined-github/blob/main/contributing.md

### CSV

https://github.com/sindresorhus/refined-github/blob/hotfix/hotfix.csv

### SVG

image

### Markdown

image

### CSV

image

### CODE REVIEW

**Comment by fregante** [comment]
Thank you! Indeed part of that code was linked to a feature that was just removed/simplified. 

As for the existence check, it can be moved in the `excluded` array in the `features.add` call. You can refer to the other usage in the repo for reference.

File: source/features/copy-file.tsx [hunk 1]
```diff
@@ -45,26 +45,24 @@ function renderButton(): void {
...
-	if (select.exists(':is(.blob, .blob-wrapper) > .markdown-body')) {
-		delegate(document, '.rgh-md-source', 'rgh:view-markdown-source', renderButton);
-		delegate(document, '.rgh-md-source', 'rgh:view-markdown-rendered', removeButton);
-	} else {
-		renderButton();
-	}
+function isRenderedPage(): boolean {
+	const isSourcePage = select.exists('table.highlight');
+	return !isSourcePage
 }
```
Comment (yakov116) [inline source/features/copy-file.tsx:56]:
```suggestion

```

File: source/features/copy-file.tsx [hunk 2]
```diff
@@ -45,26 +45,24 @@ function renderButton(): void {
...
 
 void features.add(__filebasename, {
 	include: [
 		pageDetect.isSingleFile,
 		pageDetect.isGist,
 	],
+	exclude: [
+		isRenderedPage,
```
Comment (yakov116) [inline source/features/copy-file.tsx:64]:
```suggestion
		()=> !select.exists('table.highlight'),
```

**Review by yakov116 — CHANGES_REQUESTED** [review]
We can put it all in the exclude

**Comment by yakov116** [comment]
can you run `npx xo --fix` that should fix the list issue

**Comment by roottool** [comment]
I forgot to check my commit by lint. Thank you for teaching how to fix it.

**Review by fregante — APPROVED** [review]

**Review by yakov116 — APPROVED** [review]
Untested but LGTM

**Comment by fregante** [comment]
どうもありがとう~~ミスターロボット~~ _@roottool_ 🙇‍♂️
