### PR TITLE
Fix sticky file header tooltips

### LINKED ISSUE #1295: Markdown rich diff tooltip appears underneath diff settings bar
image

Steps to repro:

1. Open a diff with markdown changes (e.g. https://github.com/dcwither/react-editable-decorator/pull/4/files?utf8=%E2%9C%93&diff=unified&w=1&short_path=04c6e90#diff-04c6e90faac2675aa89e2176d2eec7d8)
2. Scroll down until the button is sticking to the top of the screen
3. Hover over the button

Expected Behavior:

The tooltip either appears below the button or on top of the toolbar

Actual Behavior:

The tooltip appears underneath the PR toolbar.

System Info:
OS X 10.13.4
Chrome Version 65.0.3325.181 (Official Build) (64-bit)

### PR DESCRIPTION
**Pull request by wsmd**
There's a minor issue causing tooltips of elements in the sticky file header (`.file-header`) to be cut-off. This happens because of the `sticky` position that Refined Github applies to the header.

### A single file

screen shot 2018-10-13 at 5 18 51 pm

### Pull Request files

screen shot 2018-10-13 at 5 20 02 pm

## Solution

This PR attempts to resolve the issue by adding a workaround that reverses the direction of the tooltips. This only applies to:

- A single file page
- Pull Requests files page

https://github.com/sindresorhus/refined-github/blob/f8abd1e5d7c9d3b45bf3f49e58244e01b22938ca/source/content.css#L666-L668

https://github.com/sindresorhus/refined-github/blob/f8abd1e5d7c9d3b45bf3f49e58244e01b22938ca/source/content.css#L673-L675

### After

screen shot 2018-10-13 at 5 24 01 pm

screen shot 2018-10-13 at 5 23 32 pm

---

Closes #1295 (also see: #1308, #689)

### CODE REVIEW

File: source/content.js [hunk 1]
```diff
@@ -299,6 +300,10 @@ function ajaxedPagesHandler() {
 		enableFeature(extendDiffExpander);
 	}
 
+	if (pageDetect.isSingleFile() || pageDetect.isPRFiles()) {
+		enableFeature(fixStickyFileHeaderTooltips);
```
Comment (wsmd) [inline source/content.js]: I'm not sure if this the right place to call this script, or if the script should be added to `/features`, because this isn't necessary a "feature", but rather a fix for another feature – the sticky file-header, that is. Any thoughts?

File: source/features/fix-sticky-file-header-tooltips.js [hunk 2]
```diff
@@ -0,0 +1,21 @@
+import select from 'select-dom';
+
+const oppositeDirections = {
+	'tooltipped-n': 'tooltipped-s',
+	'tooltipped-ne': 'tooltipped-se',
+	'tooltipped-nw': 'tooltipped-sw'
```
Comment (wsmd) [inline source/features/fix-sticky-file-header-tooltips.js]: https://styleguide.github.com/primer/components/tooltips/#tooltip-direction

**Comment by wsmd** [comment]
I also noticed that some tooltips related to this were intentionally removed (https://github.com/sindresorhus/refined-github/issues/689#issuecomment-326825049, #799, #1234) to get around this issue. Could we use this workaround/idea instead, and restore those tooltips?

File: source/features/fix-sticky-file-header-tooltips.js [hunk 3]
```diff
@@ -0,0 +1,21 @@
...
+};
+
+export default function () {
+	for (const el of select.all('.file-header [class*=tooltipped-n]')) {
+		let direction;
```
Comment (bfred-it) [inline source/features/fix-sticky-file-header-tooltips.js]: Lo-fi one-liner to replace everything in this loop

```js
el.className = el.className.replace('tooltipped-n', 'tooltipped-s');
```

File: source/content.js (hunk 1 above)
Comment (bfred-it) [reply source/content.js]: That's right, I think _if_ this PR gets accepted, it will have to becomes its own feature: `sticky-file-headers` or even just `sticky-headers` that injects the CSS

https://github.com/sindresorhus/refined-github/blob/f8abd1e5d7c9d3b45bf3f49e58244e01b22938ca/source/content.css#L666-L668

and also fixes the issues it causes.

That, as previously mentioned, only if it's too much trouble to fix with CSS alone, which would be preferable.

File: source/features/fix-sticky-file-header-tooltips.js (hunk 3 above)
Comment (wsmd) [reply source/features/fix-sticky-file-header-tooltips.js]: I like how explicit the current implementation is, but I understand that it might be a bit too verbose. 👍 

I'll replace it with your suggestion, and probably add some comments for future maintainers to explain what it's exactly doing, especially that, at a glance, `el.className.replace` looks very close to `el.classList.replace` but it behaves very differently.

File: source/content.css [hunk 4]
```diff
@@ -24,20 +24,8 @@
...
-[aria-label='Delete this file']::before,
-[aria-label='Delete this file']::after,
-[aria-label='Edit this file']::before,
-[aria-label='Edit this file']::after,
 [aria-label='Edit comment']::before,
 [aria-label='Edit comment']::after,
-[aria-label='Open this file in GitHub Desktop']::before,
-[aria-label='Open this file in GitHub Desktop']::after,
-[aria-label$='branch to make changes.']::before,
-[aria-label$='branch to make changes.']::after,
```
Comment (wsmd) [inline source/content.css]: Since I got a thumbs up from @bfred-it on https://github.com/sindresorhus/refined-github/pull/1581#issuecomment-429579742, I went ahead and reverted all existing overrides that were hiding the tooltips.

Tooltips should look like this now 🎉 

screen shot 2018-10-13 at 11 48 55 pm
screen shot 2018-10-13 at 11 51 43 pm
screen shot 2018-10-13 at 11 51 50 pm
screen shot 2018-10-13 at 11 52 08 pm
screen shot 2018-10-13 at 11 52 25 pm

Comment (bfred-it) [reply source/content.css]: The last two can still be hidden. The tool tips don’t add any more information and the icons are obvious.

Comment (wsmd) [reply source/content.css]: > The last two can still be hidden. 

I agree 👌. While _most_ of the tooltips listed there (now removed) were added because of this specific issue within `file-header`, some other tooltips, like the notification indicator for example, can be redundant.

As for `[aria-label='Edit comment']` tooltip, it looks like there's currently a "bug" in Github (it could be intentional 🤷‍♂️) that's causing tooltips within dropdown items not to show up due to `overflow: hidden` applied on `dropdown-item`.

So I'm not sure if we should remote or keep it. It's hidden by default; with or without the extension. In case this was resolved by Github at some point, we would probably want to continue to hide it, since it's not adding any additional information.

screen shot 2018-10-14 at 3 49 42 pm

screen_shot_2018-10-14_at_3_30_35_pm

screen shot 2018-10-14 at 3 30 30 pm

**Comment by bfred-it** [comment]
A couple of things I'd rather see:

- `document.documentElement.classList.add('rgh-sticky-header') instead of selecting all elements manually (which wouldn't work on files that load later on big diffs)
- use `select.all('.file-header [class*=tooltipped-n], .table-list-header [class*=tooltipped-n]')` in the main loop

**Comment by wsmd** [comment]
oooh absolutely! good catch on the first point!

I'll also rename the `sticky-file-header` to `make-headers-sticky` for consistency with `make-discussion-sidebar-sticky`. This feature is also for search headers, not just file headers. Let me know what you think.

**Comment by bfred-it** [comment]
Better yet... this whole feature can be left in the CSS by just overriding the position via CSS:

```css
.file-header [class*=tooltipped-n]:before,
.table-list-header [class*=tooltipped-n]:before { 
    top: auto !important;
    bottom: -5px !important;
    transform: rotate(180deg)
}

.file-header [class*=tooltipped-n]:after,
.table-list-header [class*=tooltipped-n]:after { 
    top: 100% !important;
    bottom: auto  !important;
    margin-top: 5px  !important;
}
```

**Comment by wsmd** [comment]
Aside from making this whole a thing its own feature, which isn't bad. I'm curious, why do you think this approach is better than the following?

```js
for (const el of select.all('.file-header [class*=tooltipped-n]')) {
  el.className = el.className.replace('tooltipped-n', 'tooltipped-s');
}
```

I feel like renaming is `tooltipped-n*` to `tooltipped-s*` is likely to be future proof. If Github decides to change a tiny of their CSS, this extension has to be updated if we went the manually hard coding CSS properties.

File: source/content.js [hunk 5]
```diff
@@ -299,6 +300,16 @@ function ajaxedPagesHandler() {
...
 	}
 
+	if (
+		pageDetect.isIssueList() ||
+		pageDetect.isIssueSearch() ||
+		pageDetect.isPR() ||
+		pageDetect.isPRSearch() ||
+		pageDetect.isSingleFile()
+	) {
+		enableFeature(makeHeadersSticky);
```
Comment (wsmd) [inline source/content.js]: I'll move this to `onDomReady` since the original styles were applied globally anyways. I don't think there's a need to limit this to certain pages.

**Comment by bfred-it** [comment]
> If Github decides to change a tiny of their CSS

That's indeed a problem, but that also applies to JavaScript code and that usually requires more work to fix anyway.

The CSS-only solution is indeed "dirtier" (like my earlier suggestion to use `className.replace`) but perhaps we can agree that it's more efficient: it works across the board wherever those selectors apply, which means they also work on ajaxed-in files without further effort.

That said, the latest iteration of your PR seems rather lean so let's see what others say.

File: source/content.css (hunk 4 above)
Comment (bfred-it) [reply source/content.css]: All of these selectors should be restored, the icons are self-explanatory:

```css
[aria-label^='View the whole file']::before,
[aria-label^='View the whole file']::after,
[aria-label^='Change this file']::before,
[aria-label^='Change this file']::after,
[aria-label='Delete this file']::before,
[aria-label='Delete this file']::after,
[aria-label='Edit this file']::before,
[aria-label='Edit this file']::after,
```

**Comment by sindresorhus** [comment]
Thanks for fixing, @wsmd :)
