### PR TITLE
`useful-not-found-page`: Show alternate links only if applicable

### LINKED ISSUE #4790: `useful-not-found-page` shows 'This object exists on the default branch' when viewing a deleted issue
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Problem breakdown:

- The `getUrlToFileOnDefaultBranch` ([called by `showDefaultBranchLink`](https://github.com/sindresorhus/refined-github/blob/b504a42cd783836b979688731a43a0a07be65bf8/source/features/useful-not-found-page.tsx#L101)) function checks if the URL is a non-404 when the 'branch' part is replaced with the default branch:

https://github.com/sindresorhus/refined-github/blob/b504a42cd783836b979688731a43a0a07be65bf8/source/features/useful-not-found-page.tsx#L60-L64

- In this case, the 'branch' part is in fact the issue number. So it changes https://github.com/octokit/rest.js/issues/558 => https://github.com/octokit/rest.js/issues/master.
- When we visit an issue page with the issue number set to a string, (e.g.: `https://github.com/octokit/rest.js/issues/master`), Github searches for issues with the string as the `author`.
- This means that the `getUrlToFileOnDefaultBranch` function does not receive a 404, and it returns https://github.com/octokit/rest.js/issues/master as a valid issue link.
- The same does not occur on discussions as it does not support this type of query.

To prevent this bug from occurring, I think we should fix the `GithubURL` class, and make sure it does not set the `branch` variable when it gets an issue link as follows:

```diff
diff --git a/source/github-helpers/github-url.ts b/source/github-helpers/github-url.ts
index e8acd411..ec4e8c53 100644
--- a/source/github-helpers/github-url.ts
+++ b/source/github-helpers/github-url.ts
@@ -77,8 +77,12 @@ export default class GitHubURL {
 
   set pathname(pathname: string) {
     const [user, repository, route, ...ambiguousReference] = pathname.replace(/^\/|\/$/g, '').split('/');
-    const {branch, filePath} = this.disambiguateReference(ambiguousReference);
-    this.assign({user, repository, route, branch, filePath});
+    if (route === 'blob' || route === 'tree') {
+      let { branch, filePath } = this.disambiguateReference(ambiguousReference);
+      this.assign({ user, repository, route, branch, filePath });
+    } else {
+      this.assign({ user, repository, route, branch: undefined, filePath: undefined });
+    }
   }
 
   get href(): string {
```

This will trigger the condition on https://github.com/sindresorhus/refined-github/blob/b504a42cd783836b979688731a43a0a07be65bf8/source/features/useful-not-found-page.tsx#L62 and the function will return, thus not showing the incorrect link.

Let me know if this sounds like an acceptable solution. If so, I'll be happy to send in a PR.

Thanks!

### Screenshot

image

Clicking on [`This object`](https://github.com/octokit/rest.js/issues/master) takes you to https://github.com/octokit/rest.js/issues/master.

### Console errors

```shell
None
```

### Example URL

https://github.com/octokit/rest.js/issues/558

### Browser(s) used

Firefox

### PR DESCRIPTION
**Pull request by gamemaker1**
## Related issues

Fixes #4790 if merged.

## What this PR does

Restores a check from https://github.com/sindresorhus/refined-github/commit/6047ca569d61638025a26f29a31ab9069b0dd108 that does not run the `showDefaultBranchLink` and `showAlternateLink` functions if the URL is not a `blob`/`tree`/`edit` one.

## Test URLs

From the original issue:

https://github.com/octokit/rest.js/issues/558

### CODE REVIEW

File: source/features/useful-not-found-page.tsx [hunk 1]
```diff
@@ -145,13 +145,16 @@ async function showAlternateLink(): Promise<void> {
...
-	if (parts.length <= 1 || !select.exists('[alt*="This is not the web page you are looking for"]')) {
+	if (parts.length < 2) {
 		return false;
 	}
 
 	void showMissingPart();
-	void showDefaultBranchLink();
-	void showAlternateLink();
+
+	if (['tree', 'blob', 'edit'].includes(parts[2])) {
```
Comment (fregante) [inline source/features/useful-not-found-page.tsx:154]: If we had [a `required` field](https://github.com/sindresorhus/refined-github/issues/4008#issuecomment-812843149), I'd have rather used the regular `isSingleFile`/etc as suggested my comment

```js
	{
		include: [is404],
		require: [() => parseCurrentURL().length > 1],
		init: showMissingPart
	},
	{
		include: [is404],
		require: [
			isSingleFile,
			isTree,
			isEditingFile,
		],
		init: () => {showDefaultBranchLink(); showAlternateLink() }
	},
```

File: source/features/useful-not-found-page.tsx [hunk 2]
```diff
@@ -145,13 +145,16 @@ async function showAlternateLink(): Promise<void> {
 
 function init(): false | void {
 	const parts = parseCurrentURL();
-	if (parts.length <= 1 || !select.exists('[alt*="This is not the web page you are looking for"]')) {
```
Comment (yakov116) [inline source/features/useful-not-found-page.tsx:148]: If I remember correctly we needed this to detect if it was a 404

Comment (yakov116) [reply source/features/useful-not-found-page.tsx:148]: Yes
https://github.com/sindresorhus/refined-github/commit/bfdad4b4ea240c93ab0c51ff4e2a71a5b3849c94
https://github.com/sindresorhus/refined-github/issues/1856

Comment (gamemaker1) [reply source/features/useful-not-found-page.tsx:148]: I tried it out with the new code, and it does not trigger the `useful-not-found-page` on the advanced search page. I think it's because the page does not count as a 404 page anymore (`pageDetect.is404`).

Comment (fregante) [reply source/features/useful-not-found-page.tsx:148]: > If I remember correctly we needed this to detect if it was a 404

Yeah, and that seems wrong. We already have a `is404` that should that. If it doesn't work, _that_ should be fixed. But by the looks of it, `is404` already does not include the linked page.

Comment (fregante) [reply source/features/useful-not-found-page.tsx:148]: https://github.com/sindresorhus/refined-github/issues/4008#issuecomment-894979392
