### PR TITLE
Fix `format-conversation-titles`

### LINKED ISSUE #3458: `format-conversation-titles` is not very reliable
1. Visit an issue like the current one, but that you can edit
2. Change the issue title (or add/remove a tag)

The formatting is sometimes lost. Sometimes it appears a second later, sometimes it doesn't

GitHub only replaces the text node, so we can't use `selector-observer`

### PR DESCRIPTION
**Pull request by artusm**
Thanks for contributing! 🍄

1. LINKED ISSUES:
   Closes #3458

2. TEST URLS:

3. SCREENSHOT:
   BeforeBefore

   AfterAfter

### CODE REVIEW

File: source/features/format-conversation-titles.tsx [hunk 1]
```diff
@@ -23,6 +43,10 @@ void features.add({
 		pageDetect.isIssue
 	],
 	init() {
-		observeElement(select('#partial-discussion-header')!.parentElement!, init);
```
Comment (fregante) [inline source/features/format-conversation-titles.tsx:26]: What if we just change this call to include subtree: true? I don’t like to use it on whole documents, but here the base element is just the header. Would that work?

Comment (artusm) [reply source/features/format-conversation-titles.tsx:26]: > What if we just change this call to include subtree: true? I don’t like to use it on whole documents, but here the base element is just the header.

`
observeElement(select('#partial-discussion-header')!, init, {});
`

Comment (artusm) [reply source/features/format-conversation-titles.tsx:26]: > What if we just change this call to include subtree: true? I don’t like to use it on whole documents, but here the base element is just the header.

``` javascript
observeElement(select('#partial-discussion-header')!, init, {
	subtree: true
});
```
> Would that work?

No, because GitHub replaces whole header element on new events (a new message, title, etc).
Peek 2020-08-19 12-25

Comment (artusm) [reply source/features/format-conversation-titles.tsx:26]: We can use `onReplacedElement`

``` javascript
		init();
		headerWrapper = select('#partial-discussion-header')!.parentElement!;

		headerWrapper.addEventListener('submit', submitHandler);
	},
	additionalListeners: [
		() => void onReplacedElement('#partial-discussion-header', init)
	],
```

Comment (fregante) [reply source/features/format-conversation-titles.tsx:26]: > because GitHub replaces whole header element on new events 

That doesn’t sound right, I just pushed a comment and changed the title (in another tab) and the feature kept working after the updates.

Comment (fregante) [reply source/features/format-conversation-titles.tsx:26]: I think you mistakenly dropped `parentElement`

> ```js
> observeElement(select('#partial-discussion-header')!, init, {
> 	subtree: true
> });
> ```

The code should be

```diff
- observeElement(select('#partial-discussion-header')!.parentElement!, init);
+ observeElement(select('#partial-discussion-header')!.parentElement!, init, {
+ 	subtree: true
+ });
```

Comment (artusm) [reply source/features/format-conversation-titles.tsx:26]: > I think you mistakenly dropped `parentElement`

No, it wasn't a mistake. I just thought you were talking
> I don’t like to use it on whole documents

about

``` javascript 
observeElement(select('#partial-discussion-header')!.parentElement!
```

Screenshot_20200819_142700

Comment (artusm) [reply source/features/format-conversation-titles.tsx:26]: > The code should be

Peek 2020-08-19 14-59

Comment (artusm) [reply source/features/format-conversation-titles.tsx:26]: > The code should be

It works without

`
:not(.rgh-formatted-title)
`

Comment (artusm) [reply source/features/format-conversation-titles.tsx:26]: with `:not(.rgh-formatted-title)`
Peek 2020-08-19 15-11
without `:not(.rgh-formatted-title)`
Peek 2020-08-19 15-10

Comment (fregante) [reply source/features/format-conversation-titles.tsx:26]: Indeed, that should be dropped. In this case:

```js
for (const title of select.all('.js-issue-title')) {
	if (!select.exists('a, code', title)) {
		domFormatters.linkifyIssues(title);
		domFormatters.parseBackticks(title);
	}
}

**Review by fregante — APPROVED** [review]
