### PR TITLE
Fix: "Done" click is ignored when `select-notifications` is open

### LINKED ISSUE #4753: `select-notifications` should allow clicking on Done and others even if the dropdown is open
This is because the dropdown is a modal, which is fine, but this makes clicking on the actions a bit annoying since that's exactly what will come after selecting some notifications.

Notice how the first click on **Done** is "ignored"

https://user-images.githubusercontent.com/1402241/131730861-cf07a794-7169-4caa-b239-8885ede0f192.mov

cc @cheap-glitch 

## URL

https://github.com/notifications

## Browser

Safari

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #4753 

## Test URLs
https://github.com/notifications

## Screenshot

https://user-images.githubusercontent.com/46634000/133922795-289fb9b2-1ea9-4b03-b3b7-b3cac7152e36.mp4

### CODE REVIEW

File: source/features/select-notifications.tsx [hunk 1]
```diff
@@ -150,10 +152,17 @@ function createDropdown(): JSX.Element {
 	);
 }
 
+function closeDropdown(): void {
+	select('.rgh-select-notifications[open] summary')?.dispatchEvent(new MouseEvent('click'));
```
Comment (fregante) [inline source/features/select-notifications.tsx:156]: More compact, no events, simple selector

```suggestion
	select('.rgh-select-notifications')?.removeAttribute('open');
```

**Review by fregante — APPROVED** [review]
