### PR TITLE
Highlight `bugs-tab` on bug issues

### LINKED ISSUE #4164: Incorrect tab gets highlighted when opening an issue in the bugs section
## STR:
1. Goto https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+is%3Aopen+sort%3Aupdated-desc+label%3Abug.
2. Notice that the tab highlighted on the top is Bugs
3. Open any active issue, the tab highlighted switches to Issues.

Shouldn't the tab highlighted be the bugs tab?

## Video:  

https://user-images.githubusercontent.com/31387795/112757564-e371f800-9007-11eb-98a9-ed645fd6b30b.mov

### PR DESCRIPTION
**Pull request by yakov116**
Fixes #4164 

## Test URLs
Any Bug issue
https://github.com/sindresorhus/refined-github/issues/4183

## Screenshot

image

### CODE REVIEW

File: source/features/bugs-tab.tsx [hunk 1]
```diff
@@ -11,6 +11,24 @@ import {getRepo} from '../github-helpers';
...
 import abbreviateNumber from '../helpers/abbreviate-number';
 
+const cacheKey = (): string => __filebasename + ':' + getRepo()!.nameWithOwner;
+
+async function highlightBugsTabOnIssuePage(): Promise<void | false> {
+	if (!await cache.get<boolean>(cacheKey())) {
+		return false;
+	}
+
+	const sideBarLables = await elementReady('#partial-discussion-sidebar .sidebar-labels');
```
Comment (fregante) [inline source/features/bugs-tab.tsx:21]:
```suggestion
	const sidebarLables = await elementReady('#partial-discussion-sidebar .sidebar-labels');
```

File: source/features/bugs-tab.tsx [hunk 2]
```diff
@@ -11,6 +11,24 @@ import {getRepo} from '../github-helpers';
 import SearchQuery from '../github-helpers/search-query';
 import abbreviateNumber from '../helpers/abbreviate-number';
 
+const cacheKey = (): string => __filebasename + ':' + getRepo()!.nameWithOwner;
+
+async function highlightBugsTabOnIssuePage(): Promise<void | false> {
+	if (!await cache.get<boolean>(cacheKey())) {
```
Comment (fregante) [inline source/features/bugs-tab.tsx:17]: Use `countBugs()`, it's a memoized promise so it'll work without race conditions.

File: source/features/bugs-tab.tsx [hunk 3]
```diff
@@ -11,6 +11,24 @@ import {getRepo} from '../github-helpers';
...
+		return false;
+	}
+
+	const sideBarLables = await elementReady('#partial-discussion-sidebar .sidebar-labels');
+	const hasBugLabel = select.exists('.IssueLabel[href$="/bug" i]', sideBarLables);
```
Comment (fregante) [inline source/features/bugs-tab.tsx:22]: You can merge these. Since _change_ is only needed if **it exists**, waiting until dom-ready is fine. 

Likewise, generally I assume that if an issue is a bug _now_, it will still be a bug when you go _back_ to it, so the  `selected` tab doesn't necessarily need to be updated.

Maybe just:
```js
	if (!await elementReady('.IssueLabel[href$="/bug" i]')) {
		return false
	}
```

File: source/features/bugs-tab.tsx [hunk 4]
```diff
@@ -11,6 +11,24 @@ import {getRepo} from '../github-helpers';
...
+
+	const bugsTab = select('.rgh-bug-tab');
+	bugsTab!.classList.toggle('selected', hasBugLabel);
+
+	const issuesTab = select('.UnderlineNav-item[data-hotkey="g i"]')!;
+	issuesTab.classList.toggle('selected', !hasBugLabel);
```
Comment (fregante) [inline source/features/bugs-tab.tsx:28]:
```suggestion
	bugsTab!.classList.add('selected');

	const issuesTab = select('.UnderlineNav-item[data-hotkey="g i"]')!;
	issuesTab.classList.remove('selected');
```

File: source/features/bugs-tab.tsx [hunk 5]
```diff
@@ -11,6 +12,20 @@ import {getRepo} from '../github-helpers';
 import SearchQuery from '../github-helpers/search-query';
 import abbreviateNumber from '../helpers/abbreviate-number';
 
+async function highlightBugsTabOnIssuePage(): Promise<void | false> {
+	if (await countBugs() > 0 && !await elementReady('.sidebar-labels .IssueLabel[href$="/bug" i]')) {
+		return false;
+	}
+
+	await delay(1); // Wait until the bug tab is created
```
Comment (fregante) [inline source/features/bugs-tab.tsx:20]: This is arbitrary. We should use `select(tab) ?? await oneMutation(tabBar, filter)`

Comment (yakov116) [reply source/features/bugs-tab.tsx:20]: What about
```suggestion
	await elementReady('.rgh-bug-tab', {waitForDomReady: false})
```

This is really the same thing as oneMutation

Comment (fregante) [reply source/features/bugs-tab.tsx]: hmmm this might be just about the only case where `waitForDomReady: false` is acceptable, since we handle everything in this file. I mean, not ideal, still, but maybe ok enough.

File: source/features/bugs-tab.tsx [hunk 6]
```diff
@@ -11,6 +11,19 @@ import {getRepo} from '../github-helpers';
 import SearchQuery from '../github-helpers/search-query';
 import abbreviateNumber from '../helpers/abbreviate-number';
 
+async function highlightBugsTabOnIssuePage(): Promise<void | false> {
+	if (await countBugs() > 0 && !await elementReady('.sidebar-labels .IssueLabel[href$="/bug" i]')) {
+		return false;
+	}
+
+	const bugsTab = await elementReady('.rgh-bug-tab', {stopOnDomReady: false});
```
Comment (fregante) [inline source/features/bugs-tab.tsx:19]: Probably


```suggestion
	const bugsTab = await elementReady('.rgh-bug-tab', {stopOnDomReady: false, timeout: 10000});
```

Comment (fregante) [reply source/features/bugs-tab.tsx:19]: Can be merged afterwards
