### PR TITLE
Restore `edit-readme`

### LINKED ISSUE #4195: `edit-readme` stopped working
As a consequence of them adding the TOC https://github.com/sindresorhus/refined-github/issues/4157, probably the selector changed and it's no longer found.

Try it on https://github.com/typescript-eslint/typescript-eslint/tree/chore/lerna-4/docs/getting-started

Follows #4179 and #4193, which report and fix another underlying broken part of the feature.

### PR DESCRIPTION
**Pull request by kidonng**
Fix #4195

The edit button is added into the sticky header, any issue?

## Test URLs

- New header: https://github.com/sindresorhus/refined-github
- Old header: https://github.com/sindresorhus/refined-github/tree/hotfix

## Screenshot

image

### CODE REVIEW

File: source/features/edit-readme.tsx [hunk 1]
```diff
@@ -10,7 +10,7 @@ import {isPermalink} from '../github-helpers';
 import getDefaultBranch from '../github-helpers/get-default-branch';
 
 async function init(): Promise<void | false> {
-	const readmeHeader = await elementReady('#readme .Box-header h2');
+	const readmeHeader = await elementReady('#readme .Box-title');
```
Comment (yakov116) [inline source/features/edit-readme.tsx:13]: What about GHE?

```suggestion
	const readmeHeader = await elementReady([
	'#readme .Box-title',
	'#readme .Box-header h2' // GHE #4208 
	].join());
```

Comment (kidonng) [reply source/features/edit-readme.tsx:13]: This selector works on both old and new headers.
