### PR TITLE
Fix `conflict-marker` on milestone pages

### LINKED ISSUE #4391: `conflict-marker` doesn't work in Milestone page
I found `conflict-marker` feature quite useful.
I can see conflict icon in pr page
https://github.com/the-tcpdump-group/libpcap/pulls?q=is%3Apr+is%3Aopen+sort%3Aupdated-desc+milestone%3Anext-release
conflict_marker_in_pr

but not in milestone page
https://github.com/the-tcpdump-group/libpcap/milestone/1
no_conflict_marker_in_milestone

### PR DESCRIPTION
**Pull request by yakov116**
Fixes #4391

## Test URLs
Open issues
https://github.com/the-tcpdump-group/libpcap/milestone/1
No open issues.
https://github.com/sindresorhus/eslint-plugin-unicorn/milestone/1

## Screenshot
image

### CODE REVIEW

**Comment by fregante** [comment]
😱 

why do they do this…

File: source/features/conflict-marker.tsx [hunk 1]
```diff
@@ -42,6 +43,11 @@ function getPRConfig(prIcon: Element): PRConfig {
 }
 
 async function init(): Promise<false | void> {
+	// Milestone issues are lazy-loaded
```
Comment (yakov116) [inline source/features/conflict-marker.tsx:46]: Comment is good?
