### PR TITLE
Fix adding toggle files button on repo root

### LINKED ISSUE #1202: Toggle files button on repo root is broken
image

---------

Loading commit information takes some time, but https://github.com/sindresorhus/refined-github/blob/b5f1657ca231843cc53dc4addd1b3b74919df4df/source/features/add-toggle-files-button.js#L21-L25 immediately tries to append the toggle files button to container that doesn't yet exist!

------------

Doing `await safeElementReady('.commit-tease .float-right');` would not work too as https://github.com/sindresorhus/refined-github/blob/b5f1657ca231843cc53dc4addd1b3b74919df4df/source/libs/utils.js#L54-L62
cancels `waiting` immediately after page load.

### PR DESCRIPTION
**Pull request by ramlmn**
Closes #1202.

### CODE REVIEW

File: source/features/add-toggle-files-button.js [hunk 1]
```diff
@@ -19,7 +24,11 @@ function addButton() {
 }
 
 export default function () {
-	if (!select.exists('.rgh-toggle-files')) {
-		addButton();
-	}
+	observeEl(commitTease, async () => {
+		await elementReady(commitTeaseTarget);
```
Comment (bfred-it) [inline source/features/add-toggle-files-button.js]: I don’t think we need this. We’re already observing the container. If it doesn’t exist now, it will exist at the next childList change, right?

File: source/features/add-toggle-files-button.js [hunk 2]
```diff
@@ -1,10 +1,15 @@
 import {h} from 'dom-chef';
 import select from 'select-dom';
 import delegate from 'delegate';
+import elementReady from 'element-ready';
 import * as icons from '../libs/icons';
+import observeEl from '../libs/simplified-element-observer';
+
+const commitTease = '.commit-tease';
+const commitTeaseTarget = commitTease + ' .float-right';
```
Comment (bfred-it) [inline source/features/add-toggle-files-button.js]: Over-variablization 😅

File: source/features/add-toggle-files-button.js (hunk 1 above)
Comment (ramlmn) [reply source/features/add-toggle-files-button.js]: Observing the container doesn't just cut it. We still need to wait for `.float-right` element to be available in DOM (I tried with and without `elementReady`, also tried rAF and double rAF too)

Comment (bfred-it) [reply source/features/add-toggle-files-button.js]: If it's not enough, then it's not observing the right container. The point of `observeEl` is to wait for the browser to tell us when new elements appear, so combining it with `elementReady` isn't right

Comment (ramlmn) [reply source/features/add-toggle-files-button.js]: Process:
* Page loads (with somewhat empty `.commit-tease` element
* Ajax request to recent commit information
* Replace content of `.commit-tease` with the new HTML

----------------

`observeEl` watches for `.commit-tease` to change (when it's content is replaced), then it takes some time (unknown) for the `.commit-tease .float-right` element to be available in DOM (i.e., uses `await elementReady` for each change in `.commit-tease`).

Comment (bfred-it) [reply source/features/add-toggle-files-button.js]: `.commit-tease` is the wrong element to observe.

```
view-source:https://github.com/sindresorhus/refined-github
```

It's a `include-fragment` that is removed, so you can't observe it directly because the event we're waiting for is when `include-element` itself is removed. You probably have to observe `.repository-content, which is its parent.

Comment (ramlmn) [reply source/features/add-toggle-files-button.js]: > You probably have to observe .repository-content, which is its parent

That worked (atleast for me)!
