### PR TITLE
Restore `vertical-front-matter`

### LINKED ISSUE #4273: `vertical-front-matter` is broken
https://github.com/sindresorhus/refined-github/blob/main/.github/ISSUE_TEMPLATE/bug_report.md

No errors in the console. Tested in Safari

Screen Shot

### PR DESCRIPTION
**Pull request by kidonng**
Fix #4273

There isn't a selector which tells us it's a front matter or not, so we are on our own.

I come up with some rules that should handle most cases:

- The table should be the first element
- The table should only have one row in the body
- The head row and the body row should have the same number of cells

Suggestions welcome. Honestly I don't want to drop this feature just because we don't have a nice way to support it :(

## Test URLs

- With front matter: https://github.com/gatsbyjs/gatsby/blob/HEAD@%7B2020-07-08T14:12:43Z%7D/docs/blog/2020-07-07-wordpress-source-beta/index.mdx
image
- Invalid table as first element: https://github.com/kidonng/refined-github/blob/8bec852e016d10a574b1a456174139d6bb9e6c99/test.md
image

- Valid table, but not as first element: https://github.com/kidonng/refined-github/blob/798efec7e082531a8ed99aae5d47d06c31f8cbee/test.md

image

### CODE REVIEW

**Comment by fregante** [comment]
There are now 4 `select` here, `headRow` and `headers` are essentially doing the same thing. Any other improvement possible?

**Comment by kidonng** [comment]
I managed to cut down all extra selects 🎉

File: source/features/vertical-front-matter.tsx [hunk 1]
```diff
@@ -9,15 +9,24 @@ import features from '.';
 const hasFrontMatter = (): boolean => pageDetect.isSingleFile() && /\.(mdx?|mkdn?|mdwn|mdown|markdown|litcoffee)$/.test(location.pathname);
 
 function init(): void | false {
-	const table = select('[data-table-type="yaml-metadata"]')!;
+	const table = select('.markdown-body > table:first-child');
```
Comment (fregante) [inline source/features/vertical-front-matter.tsx:12]: This will create issues, but hopefully first-child 2-rows tables are rare enough 😬

File: source/features/vertical-front-matter.tsx [hunk 2]
```diff
@@ -9,15 +9,24 @@ import features from '.';
...
+	}
+
 	const headers = select.all(':scope > thead th', table);
 	if (headers.length <= 4) {
 		return false;
 	}
 
-	const values = select.all(':scope > tbody > tr > td', table);
+	const rows = select.all(':scope > tbody > tr', table);
+	if (rows.length !== 1 || headers.length !== rows[0].childElementCount) {
```
Comment (kidonng) [inline source/features/vertical-front-matter.tsx:23]: I think I missed one point: all rows always have the same number of cells, so the second check is necessary.

@yakov116 Could you add this into #4276?

```suggestion
	if (rows.length !== 1) {
```

File: source/features/vertical-front-matter.tsx (hunk 1 above)
Comment (kidonng) [reply source/features/vertical-front-matter.tsx:12]: That would still be something like key-value pairs, so the direction change won't be confusing.

File: source/features/vertical-front-matter.tsx (hunk 2 above)
Comment (yakov116) [reply source/features/vertical-front-matter.tsx:23]: Yes

Comment (fregante) [reply source/features/vertical-front-matter.tsx:23]: I was going to say this, but technically tables could have spanning headers:


<table>
<tr>
	<th colspan="3"> title
<tr>
	<td>1
	<td>2
	<td>3
</table>

I thought it was an extra check to ensure we got exact tables

File: source/features/vertical-front-matter.tsx (hunk 1 above)
Comment (fregante) [reply source/features/vertical-front-matter.tsx:12]: True, but if someone expect a horizontal table and sees a vertical table it can still cause confusion

File: source/features/vertical-front-matter.tsx (hunk 2 above)
Comment (kidonng) [reply source/features/vertical-front-matter.tsx:23]: 🤦You are right, I forgot there's `colspan`. So the check is indeed necessary (not possible through Markdown though).

@yakov116 sorry for the trouble but we better revert the change 😅
