### PR TITLE
Fix wrapping too long PR title on PR files tab

### LINKED ISSUE #2202: Bug on pull request files tab
**RGH Version:** 19.6.30 (Chrome)

GitHub recently added a new feature for marking files as viewed when reviewing a pull request.
The following bugs happen when Refined GitHub is enabled.
Confirmed by disabling all browser extensions but RGH.

1. When the length of the PR title + number is too long,
	it wraps the right-floated elements to a new line.
2. When the filename of the file currently in view is too long,
	the scrolling "file actions" bar is malformed (for lack of a better term).
	**Edit:** It's possible that it only happens if the **first** filename is too long, as on the example PR below, the second filename is even longer, yet it looks just fine.

**Edit 2:** When I disable [`faster-pr-diff-options`](https://github.com/sindresorhus/refined-github/blob/19.6.30/source/features/faster-pr-diff-options.tsx) it fixes both bugs.

This is an example PR: https://github.com/pymedusa/Medusa/pull/6893/files

---
## RGH **disabled**
chrome_XwwqDu9Y0Q

---
## RGH **enabled**
chrome_ePXSiihJ2e

### PR DESCRIPTION
**Pull request by jerone**
# Description
Trim the PR title on the PR files tab.

# Closes 
Fixes #2202.

# Test
* Fixed on: https://github.com/sindresorhus/refined-github/pull/2229/files
* N/A on: https://github.com/sindresorhus/refined-github/pull/2229/commits/b8b9a3394d9aa667ad9c2576ff5fd381147c4960

### CODE REVIEW

File: source/features/faster-pr-diff-options.tsx [hunk 1]
```diff
@@ -72,6 +72,12 @@ function init(): false | void {
 		)
 	);
 
+	// Trim title
+	const prTitle = select('.pr-toolbar .js-issue-title');
+	if (prTitle && select.exists('.pr-toolbar progress-bar')) { // Only review view has progress-bar
+		prTitle.style.maxWidth = '24em';
```
Comment (sharkykh) [inline source/features/faster-pr-diff-options.tsx]: That said, we could also set the title attribute for a tooltip with the full PR title on hover.
```suggestion
		prTitle.style.maxWidth = '24em';
		prTitle.title = prTitle.textContent;
```

File: source/features/faster-pr-diff-options.tsx [hunk 2]
```diff
@@ -72,6 +72,13 @@ function init(): false | void {
...
+		prTitle.title = prTitle.textContent;
```
Comment (sharkykh) [inline source/features/faster-pr-diff-options.tsx]: Oops :)
```suggestion
		prTitle.title = prTitle.textContent!;
```
