### PR TITLE
Correctly display `hide-comments-faster` on small viewports

### LINKED ISSUE #4032: `hide-comments-faster` is broken on <700px viewports
1. Resize your window to be 700px wide or less
1. Visit an issue or PR on a repo you're a collaborator to / owner of
2. Open its context menu
3. Select "Hide comment"
4. Notice:

Screen Shot 8

This is probably due to a mobile-only flex class. The class should be removed

### PR DESCRIPTION
**Pull request by carl-evans**
Thanks for contributing! 🍄

1. LINKED ISSUES:
   Does this PR close/fix an existing issue? Write something like `Closes #10`
Closes #4032

2. TEST URLS:
   Can you please explain what Tests this refers to? I checked readme.md and couldn't find anything. Happy to add these in though.

3. SCREENSHOT:
   Add a screenshot here if your PR makes visual changes
Screenshot 2021-02-27 at 21 31 45

### CODE REVIEW

**Comment by fregante** [comment]
> Can you please explain what Tests this refers to? I checked readme.md and couldn't find anything. Happy to add these in though.

Most Refined GitHub features apply to only some pages. A "test URL" in this case means: Where did you test this PR? Where can a reviewer test this PR to ensure that this issue has been fixed?

File: source/features/hide-comments-faster.tsx [hunk 1]
```diff
@@ -17,6 +17,9 @@ function generateSubmenu(hideButton: Element): void {
 	const comment = hideButton.closest('.unminimized-comment')!;
 	const hideCommentForm = select('.js-comment-minimize', comment)!;
 
+	// remove the d-flex class from the comment form
```
Comment (fregante) [inline source/features/hide-comments-faster.tsx:20]: Comments should be a word-for-word explanation of the code, they should explain why the code exists or what it does. In this case it's not really needed since it's self-explanatory that it removes the class because it's not the behavior we want.

**Comment by fregante** [comment]
Thanks for contributing!
