### PR TITLE
Meta: Improve logs

### LINKED ISSUE #4287: Hide errors when logged out
❌ Refined GitHub → set-default-repositories-type-to-sources → 
```js
TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at refined-github.js:3850
    at new Promise (<anonymous>)
    at oneMutation (refined-github.js:3846)
    at onProfileDropdownLoad (refined-github.js:4636)
    at async chrome-extension:/hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:6004
    at async runFeature (refined-github.js:1936)
    at async setupPageLoad (refined-github.js:1949)
    at async chrome-extension:/hlepfoohegkhhmjieoechaddaejaokhf/build/refined-github.js:1982 
```
Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Failed%20to%20execute%20'observe'%20on%20'MutationObserver'%3A%20parameter%201%20is%20not%20of%20type%20'Node'.

Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60set-default-repositories-type-to-sources%60%3A%20Failed%20to%20execute%20'observe'%20on%20'MutationObserver'%3A%20parameter%201%20is%20not%20of%20type%20'Node'.

As noted on RG itself - _RG is only expected to work when you're logged in to Github_

### PR DESCRIPTION
**Pull request by fregante**
Closes #4287 
Addresses https://github.com/sindresorhus/refined-github/pull/4276#issuecomment-828204951

### CODE REVIEW

File: source/features/index.tsx [hunk 1]
```diff
@@ -85,11 +93,20 @@ const globalReady: Promise<RGHOptions> = new Promise(async resolve => {
...
 	if (select.exists('html.refined-github')) {
-		console.warn('Refined GitHub has been loaded twice. If you didn’t install the developer version, this may be a bug. Please report it to: https://github.com/sindresorhus/refined-github/issues/565');
+		console.warn(stripIndent(`
+			Refined GitHub has been loaded twice. This may be because:
+
+			• You loaded the developer version, or
+			• The extension just updated
+
+			If you see this at every load, please open an issue mentioning the browser you're using and the URL where this appears.
+		`));
```
Comment (fregante) [inline source/features/index.tsx:109]: ## Improved copy for https://github.com/sindresorhus/refined-github/issues/565

That issue is outdated and people shouldn't refer to it. A new issue is better.

File: source/features/close-out-of-view-modals.tsx [hunk 2]
```diff
@@ -29,9 +29,9 @@ function menuActivatedHandler(event: delegate.Event): void {
 	const details = event.target as HTMLDetailsElement;
 
 	// Safety check #3742
-	if (!details.open && lastOpen > Date.now() - 1000) {
+	if (!details.open && lastOpen > Date.now() - 500) {
 		delegation!.destroy();
-		features.error(__filebasename, 'Modal was closed too quickly. Disabling feature');
+		console.warn(`The modal was closed too quickly. Disabling ${__filebasename} for this session.`);
```
Comment (fregante) [inline source/features/close-out-of-view-modals.tsx:34]: ## Reduced error for `close-out-of-view-modals`

It would show a red error if you were fast enough. Now the timeout is reduced and it just shows a warning.

Screen Shot 10

File: source/features/index.tsx [hunk 3]
```diff
@@ -85,11 +93,20 @@ const globalReady: Promise<RGHOptions> = new Promise(async resolve => {
 	}
 
 	if (document.body.classList.contains('logged-out')) {
-		console.warn('%cRefined GitHub%c is only expected to work when you’re logged in to GitHub.', 'font-weight: bold', '');
+		console.warn('Refined GitHub is only expected to work when you’re logged in to GitHub. Errors will not be shown.');
+		features.error = () => {/* No logging */};
+		logError = () => {/* No logging */};
 	}
```
Comment (fregante) [inline source/features/index.tsx:99]: ## No more errors for logged-out users

Only the warning will be shown

Screen Shot 8

File: source/features/index.tsx [hunk 4]
```diff
@@ -45,32 +45,40 @@ interface InternalRunConfig {
...
+
+		URL: ${location.href}
+
+		\`\`\`
+		${error instanceof Error ? error.stack : error as string}
+		\`\`\`
+	`));
+	console.group('Open an issue');
+	console.log(newIssueUrl.href);
+	console.groupEnd();
```
Comment (fregante) [inline source/features/index.tsx:78]: ## Auto-filled issue template

Screen Shot 6

File: source/features/index.tsx [hunk 5]
```diff
@@ -45,32 +45,40 @@ interface InternalRunConfig {
...
-		...extras,
-		stripIndent(`
-			Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+${encodeURIComponent(message)}
-
-			Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=${encodeURIComponent(`\`${id}\`: ${message}`)}
-		`)
-	);
-}
+	// Don't change this to `throw Error` because Firefox doesn't show extensions' errors in the console
+	console.group('❌', id, version, pageDetect.isEnterprise() ? 'GHE →' : '→', error);
```
Comment (fregante) [inline source/features/index.tsx:59]: # Better layout for errors

- no repeated "Refined GitHub" text
- no repeated stack
- includes RG version
- includes "GHE" if it's on GHE

Screen Shot 2

File: source/features/index.tsx [hunk 6]
```diff
@@ -45,32 +45,40 @@ interface InternalRunConfig {
...
+
+		\`\`\`
+		${error instanceof Error ? error.stack! : error as string}
+		\`\`\`
+	`));
+	console.group('Open an issue');
+	console.log(newIssueUrl.href);
+	console.groupEnd();
+
+	console.groupEnd();
```
Comment (yakov116) [inline source/features/index.tsx:80]: Is this 2 times by mistake?

Comment (fregante) [reply source/features/index.tsx:80]: There are 2 groups

File: source/features/close-out-of-view-modals.tsx (hunk 2 above)
Comment (fregante) [reply source/features/close-out-of-view-modals.tsx:34]: I doubt it because this event is always generated by the browser regardless of the origin of the click, which has a separate event
