### PR TITLE
Fix branch link broken with `/` in the branch name

### LINKED ISSUE #2049: Master branch links are broken for branches with a `/` in the branch name
Master branch links are broken for branches with a `/` in the branch name.

eg. branch `sk/dev` links to `[repo]/tree/master/dev`

bug is here: https://github.com/sindresorhus/refined-github/blob/master/source/features/branch-buttons.tsx#L78 
and here: https://github.com/sindresorhus/refined-github/blob/master/source/libs/page-detect.ts#L84

### PR DESCRIPTION
**Pull request by kevin940726**
Closes #2049 

I took the closet approach I can think of via a `<link>` tag in head which looks like follow.

```html
<link href="https://github.com/sindresorhus/refined-github/commits/master.atom" rel="alternate" title="Recent Commits to refined-github:master" type="application/atom+xml">
```

Looks like every pages have it, and we can get the current branch from it stably. Please let me know if there is any concern.

I tried getting the current branch from the dropdown menu, but they are lazily loaded. Then I tried to get it from the `title` attribute of the dropdown button, it works for branch, but not for tag. I want to have a more general solution so I took this approach.

# Test

https://github.com/kevin940726/refined-github/blob/fix/branch-buttons/.travis.yml

### CODE REVIEW

File: source/libs/utils.ts [hunk 1]
```diff
@@ -30,6 +30,15 @@ export const getRepoBranch = (): string | false => {
 	return false;
 };
 
+export const getCurrentBranch = (): string | undefined => {
+	const recentCommitsLink = select('link[title^="Recent Commits to"]')!;
+	// Will be something like https://github.com/sindresorhus/refined-github/commits/master.atom
+	const href = recentCommitsLink.getAttribute('href')!;
+	const group = /\/commits\/(.+)\.atom$/.exec(href);
+
+	return group ? group[1] : undefined;
```
Comment (bfred-it) [inline source/libs/utils.ts]:
```ts
return select('[aria-current="page"]')!
	.pathname // <user>/<repo>/tree/<branch/slashed-branch>
	.split('/')
	.slice(4) // Drops everything and including `tree`
	.join('/');
```

File: source/features/branch-buttons.tsx [hunk 2]
```diff
@@ -74,9 +72,7 @@ async function getDefaultBranchLink(): Promise<HTMLElement | undefined> {
 	if (isRepoRoot()) {
 		url = `/${getRepoURL()}`;
 	} else {
-		const urlParts = location.pathname.split('/');
-		urlParts[4] = defaultBranch; // Change branch of current blob/tree
-		url = urlParts.join('/');
+		url = location.pathname.replace(currentBranch, defaultBranch);
```
Comment (bfred-it) [inline source/features/branch-buttons.tsx]: This isn't safe, it will fail on `/sindresorhus/ava/blob/ava`

Comment (kevin940726) [reply source/features/branch-buttons.tsx]: You're right! I forgot about that, thx!

File: source/libs/utils.ts (hunk 1 above)
Comment (kevin940726) [reply source/libs/utils.ts]: LGTM, it seems to be more resilient than my approach.

Comment (kevin940726) [reply source/libs/utils.ts]: The only problem I can think of is that when we are in the repo root (`https://github.com/sindresorhus/refined-github`), the above code will yield an empty string. It might works just fine with this feature since we have another check about whether we are in repo root, but might not be appropriate for a more general utility function. Should we fallback to default branch in this case? Is it possible?

File: source/features/branch-buttons.tsx [hunk 3]
```diff
@@ -40,7 +40,7 @@ async function getTagLink(): Promise<'' | HTMLAnchorElement> {
 
 	const link = <a className="btn btn-sm btn-outline tooltipped tooltipped-ne">{icons.tag()}</a> as unknown as HTMLAnchorElement;
 
-	const currentBranch = select('.branch-select-menu .css-truncate-target')!.textContent;
```
Comment (kevin940726) [inline source/features/branch-buttons.tsx]: Actually I'm curious about why we chose to select the current branch like this before. AFAIK, it would only selected the truncated branch name but not the full name. Is there any concerns I don't know about?

Comment (bfred-it) [reply source/features/branch-buttons.tsx]: The name is only truncated via CSS so in the DOM it's still full

File: source/libs/utils.ts (hunk 1 above)
Comment (bfred-it) [reply source/libs/utils.ts]: Let's revert to `select('.branch-select-menu .css-truncate-target').textContent`, it works all the time.

Comment (kevin940726) [reply source/libs/utils.ts]: I'm still getting `branch/still-b…` instead of `branch/still-branch` by using that [here](https://github.com/simonkotwicz/refined-github/blob/branch/still-branch/.travis.yml#L6). I might have did something wrong?

Comment (bfred-it) [reply source/libs/utils.ts]: Indeed, they must have changed it. This seems to work:

```js
select('.branch-select-menu .css-truncate').title
```

Comment (kevin940726) [reply source/libs/utils.ts]: Like I stated in the PR description, I think this would only work for branch but not for tag? (I don’t have my laptop to verify now)

**Comment by sharkykh** [comment]
@bfred-it An empty file made it in:
https://github.com/sindresorhus/refined-github/blob/master/source/libs/get-current-branch.ts

**Comment by bfred-it** [comment]
Thanks! Fixed

**Comment by bfred-it** [comment]
And thanks @kevin940726 for your contribution 🥇
