### PR TITLE
Avoid showing `conversation-activity-filter` in wrong position

### LINKED ISSUE #4365: change base branch issue (`hide-useless-comments`)
**Reproduce**

1. Open a PR
2. Click the edit button to change the title/base branch
3. Open the dropdown to change the base branch
4. Observe

[Test URL](https://github.com/DevSnowflake/discord-player-extractors/pull/7)

**Screenshot**

image

**Errors**

No errors were logged to the console.

### PR DESCRIPTION
**Pull request by yakov116**
Fixes #4365
Follows https://github.com/sindresorhus/refined-github/pull/4361

## Test URLs
This PR
https://github.com/SamVerschueren/vscode-linter-xo/issues/91

## Screenshot
NONE

### CODE REVIEW

File: source/features/conversation-activity-filter.tsx [hunk 1]
```diff
@@ -147,17 +151,20 @@ function addWidget(position: Element): void {
...
-function init(): void {
-	const observer = observe(':is(.gh-header-sticky .meta, .gh-header-meta .flex-auto):not(.rgh-conversation-activity-filter)', {
-		add: addWidget
-	});
-	deinit.push(observer.abort);
+async function init(): Promise<void> {
+	// Work around for `clean-conversation-headers`
+	const mainHeaderSelector = pageDetect.isPR() ? 'relative-time' : 'span[data-issue-and-pr-hovercards-enabled]';
+	await addWidget(`#partial-discussion-header .gh-header-meta :is(clipboard-copy, ${mainHeaderSelector})`);
+	await addWidget('#partial-discussion-header .gh-header-sticky :is(clipboard-copy, relative-time)');
```
Comment (fregante) [inline source/features/conversation-activity-filter.tsx:158]: Since we’re always appending it, can we just use elementReady on `.gh-header-*` elements instead? Maybe that won’t require us to select a specific icon inside.

**Comment by fregante** [comment]
Always try to include as many references to other PRs and issues as possible so that they’re connected. I added https://github.com/sindresorhus/refined-github/pull/4361 to your post

File: source/features/conversation-activity-filter.tsx (hunk 1 above)
Comment (yakov116) [reply source/features/conversation-activity-filter.tsx:158]: The issue is not being ready. Its where at append the icon.

Unless I misunderstood you.

Comment (yakov116) [reply source/features/conversation-activity-filter.tsx:158]: @fregante?

File: source/features/conversation-activity-filter.tsx [hunk 2]
```diff
@@ -147,17 +151,20 @@ function addWidget(position: Element): void {
...
 
-function init(): void {
-	const observer = observe(':is(.gh-header-sticky .meta, .gh-header-meta .flex-auto):not(.rgh-conversation-activity-filter)', {
-		add: addWidget
-	});
-	deinit.push(observer.abort);
+async function init(): Promise<void> {
+	// Work around for `clean-conversation-headers`
+	const mainHeaderSelector = pageDetect.isPR() ? 'relative-time' : 'span[data-issue-and-pr-hovercards-enabled]';
+	await addWidget(`#partial-discussion-header .gh-header-meta :is(clipboard-copy, ${mainHeaderSelector})`);
```
Comment (fregante) [inline source/features/conversation-activity-filter.tsx:157]: If `clean-conversation-headers` can select it with this, so can the feature, right?

https://github.com/sindresorhus/refined-github/blob/b48d3ebfa0ea467aefe5d33741b364212874efbb/source/features/clean-conversation-headers.tsx#L13

Comment (yakov116) [reply source/features/conversation-activity-filter.tsx:157]: It can but the sticky will need the parent element and this will not. Unless I drop the more "secure" selector

Comment (fregante) [reply source/features/conversation-activity-filter.tsx:157]: .closest() works on itself too, so if `.flex-auto` is a div, it matches itself, so changing only this selector might not be a problem

**Comment by yakov116** [comment]
@fregante this is good to go. It works perfectly
