### PR TITLE
Fix `preview-hidden-comments` for resolved and outdated comments

### LINKED ISSUE #3647: `preview-hidden-comments` no longer works for most types
The `preview-hidden-comments` feature isn't working probably because GitHub started hiding some reasons why a comment has been hidden:

I'll add and hide comments below as a live example.

Here's the originally-allowed types for reference:

https://github.com/sindresorhus/refined-github/blob/c6c727ca571c91d1ff426e218ccadb075cdb2af6/source/features/preview-hidden-comments.tsx#L9

_Originally reported in https://github.com/sindresorhus/refined-github/pull/3621#issuecomment-707895439_

### PR DESCRIPTION
**Pull request by cheap-glitch**
Fixes #3647 

## Test URLs
https://github.com/sindresorhus/refined-github/issues/3647

## Screenshot

<table>
<tr>
	<th>Before
	<th>After
<tr>
	<td>
		
	<td>
		
</table>

### CODE REVIEW

File: source/features/preview-hidden-comments.tsx [hunk 1]
```diff
@@ -23,13 +23,13 @@ const init = (): void => {
...
 		const reason = /was marked as ([^.]+)/.exec(header.textContent!)?.[1] ?? '';
-		if (!allowedReasons.has(reason)) {
+		if (forbiddenReasons.has(reason)) {
 			continue;
 		}
 
 		header.append(
 			<span className="Details-content--open">{header.firstChild}</span>,
-			<span className="Details-content--closed">{`${upperCaseFirst(reason)} — ${commentText}`}</span>
+			<span className="Details-content--closed">{(reason.length > 0 ? upperCaseFirst(reason) + ' — ' : '') + commentText}</span>
```
Comment (cheap-glitch) [inline source/features/preview-hidden-comments.tsx:32]: Should be give up on showing the reason altogether? Since only off-topic comments can display it anyway.

**Comment by fregante** [comment]
This is not what the feature was meant to do; It should preview the comments, not add the reason where it's missing. Refer to the existing screenshots

**Comment by fregante** [comment]
I think the logic should be rewritten since the reason can't be parsed anymore. It's as simple as `if message is either off-top or minimized, preview it`

Also the preview should be:


```
Off-topic — This message is blah blah
Hidden — This message is blah blah
```

File: source/features/preview-hidden-comments.tsx [hunk 2]
```diff
@@ -22,14 +22,14 @@ const init = (): void => {
 			'.discussion-item-icon  + div' // Review Comments
 		], details)!;
 
-		const reason = /was marked as ([^.]+)/.exec(header.textContent!)?.[1] ?? '';
-		if (!allowedReasons.has(reason)) {
+		const reason = /was marked as ([^.]+)/.exec(header.textContent!)?.[1] ?? (header.textContent!.trim().endsWith('has been minimized.') ? 'duplicate' : '');
```
Comment (fregante) [inline source/features/preview-hidden-comments.tsx:25]: Probably

```suggestion
		const reason = /minimized|off-topic/.exec(header.textContent!)?.[0];
```
