### PR TITLE
Fix `fix-view-file-link-in-pr` and ignore deleted files

### LINKED ISSUE #3108: `fix-view-file-link-in-pr` breaks links to deleted files
`fix-view-file-link-in-pr` makes it easier to edit files after you click "View file", but this doesn't make sense for deleted files: there's no file to delete anymore.

By default, GitHub links to _the previous version_ of the file, before its deletion.

For this reason, deleted files should not be affected by `fix-view-file-link-in-pr`

Example: https://github.com/yakov116/TestR/pull/21/files
It normally links to: https://github.com/yakov116/TestR/blob/7f9a18b4d0f3b8627180a7cbea6513d72d85cfb0/sub/README.md
But it's changed to: https://github.com/yakov116/TestR/blob/yakov116-patch-4/sub/README.md (404)

### PR DESCRIPTION
**Pull request by yakov116**
1. LINKED ISSUES:
   Fixes #3108 

2. TEST URLS:
	Deleted File
   https://github.com/yakov116/TestR/pull/21/files
	Local File (Not deleted)
https://github.com/sindresorhus/refined-github/pull/3106/files
	None Local Files (Not deleted)
https://github.com/sindresorhus/refined-github/pull/3103/files

3. SCREENSHOT:
	None

I broke the feature (when tested it, I was testing on my own repo)

### CODE REVIEW

File: source/features/fix-view-file-link-in-pr.tsx [hunk 1]
```diff
@@ -24,13 +23,19 @@ function handleMenuOpening(event: delegate.Event): void {
 		return;
 	}
 
+	const viewFile = select<HTMLAnchorElement>('[data-ga-click^="View file"]', dropdown)!;
+
+	// If the file was deleted
+	if (viewFile.closest('[data-file-deleted="true"]')) {
```
Comment (fregante) [inline source/features/fix-view-file-link-in-pr.tsx:29]: This can be part of the `delegate` selector

File: source/features/fix-view-file-link-in-pr.tsx [hunk 2]
```diff
@@ -24,13 +23,19 @@ function handleMenuOpening(event: delegate.Event): void {
...
+
 	// This solution accounts for:
 	// - Branches with slashes in it
 	// - PRs opened from the default branch
-	const viewFile = select<HTMLAnchorElement>('[data-ga-click^="View file"]', dropdown)!;
-	const pathParts = viewFile.pathname.split('/'); // Example pathname: $owner/$repository/blob/$sha/$path_to_file.tsx
-	pathParts[4] = getCurrentBranch();
-	viewFile.pathname = pathParts.join('/');
+	const headRepo = select<HTMLAnchorElement>('.commit-ref.head-ref a')!.pathname;
+	const filepath = viewFile.pathname.split('/').slice(5).join('/'); // Example pathname: $owner/$repository/blob/$sha/$path_to_file.tsx
```
Comment (fregante) [inline source/features/fix-view-file-link-in-pr.tsx:37]:
```suggestion
	const filepath = dropdown.closest('[data-path]').dataset.path;
```

It appears to work even after renames. Example URL: https://github.com/sindresorhus/refined-github/pull/1750/files#diff-15c8cc76e8bb627ef332f633511c9c38

File: source/features/fix-view-file-link-in-pr.tsx [hunk 3]
```diff
@@ -24,13 +23,19 @@ function handleMenuOpening(event: delegate.Event): void {
...
+	}
+
 	// This solution accounts for:
 	// - Branches with slashes in it
 	// - PRs opened from the default branch
-	const viewFile = select<HTMLAnchorElement>('[data-ga-click^="View file"]', dropdown)!;
-	const pathParts = viewFile.pathname.split('/'); // Example pathname: $owner/$repository/blob/$sha/$path_to_file.tsx
-	pathParts[4] = getCurrentBranch();
-	viewFile.pathname = pathParts.join('/');
+	const headRepo = select<HTMLAnchorElement>('.commit-ref.head-ref a')!.pathname;
```
Comment (fregante) [inline source/features/fix-view-file-link-in-pr.tsx:36]: How about
```suggestion
	const headBranchUrl = select<HTMLAnchorElement>('.commit-ref.head-ref a')!.pathname;
```

**Comment by fregante** [comment]
Neat!
