### PR TITLE
Restore `close-out-of-view-modals` feature

### LINKED ISSUE #1796: `close-out-of-view-modals` currently broken
1. Click on your profile picture in the top right header
2. Scroll all the way down
3. Scroll back up, the popup didn't close

https://github.com/sindresorhus/refined-github/blob/master/source/features/close-out-of-view-modals.tsx

### PR DESCRIPTION
**Pull request by dutiyesh**
Fixes #1796

### CODE REVIEW

File: source/features/close-out-of-view-modals.tsx [hunk 1]
```diff
@@ -6,7 +6,7 @@ const observer = new IntersectionObserver(([{intersectionRatio, target}]) => {
 	if (intersectionRatio === 0) {
 		observer.unobserve(target);
 		const dropdown = select(`
-			.dropdown-details[open] summary,
+			details[open] summary,
```
Comment (bfred-it) [inline source/features/close-out-of-view-modals.tsx]: This would also select `details` in comments.

I think the new class is `details-overlay`

```suggestion
			.details-overlay[open] summary,
```

File: source/features/close-out-of-view-modals.tsx [hunk 2]
```diff
@@ -16,12 +16,12 @@ const observer = new IntersectionObserver(([{intersectionRatio, target}]) => {
 });
 
 function init() {
-	delegate('.dropdown-details, .js-menu-target', 'click', event => {
+	delegate('.select-menu-button, .js-menu-target, summary', 'click', event => {
```
Comment (bfred-it) [inline source/features/close-out-of-view-modals.tsx]: Same for `summary` here

File: source/features/close-out-of-view-modals.tsx (hunk 1 above)
Comment (dutiyesh) [reply source/features/close-out-of-view-modals.tsx]: Done.

**Comment by bfred-it** [comment]
Tested on:

- top-right profile menu
- repo Watch dropdown
- repo More dropdown
- issue sidebar selectors
- issue-list filters
- PRs' "squash and merge" dropdown 
- dropdown menu on comments
