### PR TITLE
Fix `edit-comments-faster` to only when editing is allowed

### LINKED ISSUE #4400: `edit-comments-faster` is enabled in discussions even without sufficient permissions
In https://github.com/streetcomplete/StreetComplete/discussions/2671, I see an edit icon in all comments, even though I can't actually edit those:

grafik

When clicking the button, the edit interface actually appears, but saving reloads the page and drops the changes.

### PR DESCRIPTION
**Pull request by darkred**
Fix #4400

## Test URLs

Discussions where you don't have made any comments, and you are not maintainer/collaborator,
e.g. https://github.com/streetcomplete/StreetComplete/discussions/2671

## Note to reviewers:

The issue #4400 is about this line:

https://github.com/sindresorhus/refined-github/blob/575f41a7faacd5901065cfae634ce0399658d1cb/source/features/edit-comments-faster.tsx#L11

That selector works ok in Issue pages *(it selects all your comments that you can edit)*, 
but it doesn't work ok in Discussion pages - it wrongly selects all comments).

This PR adds a check so that, if in the Discussion page there's a "`You are a (maintainer/collaborator)`" element
~~or it's in Issues page, then use the old selector,~~, or that you still can edit the page,
otherwise add to that selector this class: `.current-user` (=comments made by you) for more specificity.

### CODE REVIEW

File: source/features/edit-comments-faster.tsx [hunk 1]
```diff
@@ -8,7 +8,9 @@ import features from '.';
 
 function init(): void {
 	// Find editable comments first, then traverse to the correct position
-	observe('.js-comment.unminimized-comment .js-comment-update:not(.rgh-edit-comment)', {
+	observe((document.querySelector('.current-user span[title^="You are a"]') !== null || pageDetect.hasComments() ?
+		'.js-comment.unminimized-comment .js-comment-update:not(.rgh-edit-comment)' :
+		'.current-user.js-comment.unminimized-comment .js-comment-update:not(.rgh-edit-comment)'), {
```
Comment (yakov116) [inline source/features/edit-comments-faster.tsx:13]: I would rather a if .... return

The above code is very hard to read

Comment (darkred) [reply source/features/edit-comments-faster.tsx:13]: Do you mean to change it like this?

```js
	let selector = '.current-user.js-comment.unminimized-comment .js-comment-update:not(.rgh-edit-comment)';
	if (document.querySelector('.current-user span[title^="You are a"]') !== null || pageDetect.hasComments()) {
		selector = '.js-comment.unminimized-comment .js-comment-update:not(.rgh-edit-comment)';
	}

	observe(selector, {
```

I'm asking, because I can't see where to use `return`, 
and if I use `if ... else`, then the `unicorn/prefer-ternary` lint rule is triggered.

Comment (darkred) [reply source/features/edit-comments-faster.tsx:13]: But, the change has to be done in the selector in the `observe(` line:

https://github.com/sindresorhus/refined-github/blob/575f41a7faacd5901065cfae634ce0399658d1cb/source/features/edit-comments-faster.tsx#L11-L12

which is before the `add()`.

How can I use the `selector` after the `add()` ?

Comment (yakov116) [reply source/features/edit-comments-faster.tsx:13]: comment will be an element query based off the element

Comment (fregante) [reply source/features/edit-comments-faster.tsx:13]: We're using the selector itself to exclude comments that can't be edited, but it's failing because GitHub is including dead DOM here, so we have to improve the detection.

There are 2 types of comments that can be editable:

- every comment, if you're a moderator
- only your comment otherwise

I think we'll need something like:


```js
const preSelector = canEditDiscussion() ? '' : '.current-user';

observer(preSelector + '.js-comment.unminimized-comment .js-comment-update:not(.rgh-edit-comment)', {
```

However I'm not seeing #4400 at all

Screen Shot 6

Probably because @cheap-glitch is a collaborator there but can't edit the comments. `canEditDiscussion` needs to be created with this in mind.

**Review by fregante — CHANGES_REQUESTED** [review]

File: source/features/edit-comments-faster.tsx (hunk 1 above)
Comment (yakov116) [reply source/features/edit-comments-faster.tsx:13]: > However I'm not seeing #4400 at all

I see it 😕 on every post there is an edit button

**Comment by darkred** [comment]
First of all, for reference:
<details>
<summary>Here are the available permission levels in GitHub</summary>

Based on this page: [Access permissions on GitHub](https://docs.github.com/en/github/getting-started-with-github/learning-about-github/access-permissions-on-github) there are the following:

Personal user accounts:
- the repository owner,
- collaborators 

Organization accounts:
- owner, 
- billing manager, 
- member . 

<details>
<summary>Enterprise owners</summary>

Enterprise owners have ultimate power over the enterprise account and can take every action in the enterprise account. Billing managers can manage your enterprise account's billing settings. Members and outside collaborators of organizations owned by your enterprise account are automatically members of the enterprise account, although they have no access to the enterprise account itself or its settings.
</details>

</details>

---


&nbsp;
With my new commit I tried to make a reliable `canEditDiscussion()`:
it checks whether there's a `You are the author/collaborator` in the page (-there are posts by you in the discussion),
or otherwise (=there are no posts), but you can edit the discussion title, meaning that you have editing access.
Also, the `.current-user` has only meaning in Discussions. So:

```js
function canEditDiscussion(): boolean {
	return document.querySelector(`
	.current-user span[title^="You are the author"],
	.current-user span[title^="You are a collaborator"],
	button[aria-label="Edit discussion title"]
	`) !== null;
}

function init(): void {
	let preSelector = '';
	if (pageDetect.isDiscussion()) {
		preSelector = canEditDiscussion() ? '' : '.current-user';
	}

	observe(preSelector + ...
```

I tested it in discussions of repos where I am collaborator, in my own repo where I am author,
and in discussions where I have just commented.

--- 

My last commit is aimed to repos owned by personal user accounts.
I don't have access to Organization or Enterprise.

File: source/features/edit-comments-faster.tsx [hunk 2]
```diff
@@ -6,11 +6,21 @@ import * as pageDetect from 'github-url-detection';
 
 import features from '.';
 
+function canEditDiscussion(): boolean {
+	return document.querySelector(`
+	.current-user span[title^="You are the author"],
+	.current-user span[title^="You are a collaborator"],
+	button[aria-label="Edit discussion title"]
+	`) !== null;
```
Comment (yakov116) [inline source/features/edit-comments-faster.tsx:14]:
```suggestion
	return select.exists(`
	.current-user span[title^="You are the author"],
	.current-user span[title^="You are a collaborator"],
	button[aria-label="Edit discussion title"]
	`);
```

Comment (darkred) [reply source/features/edit-comments-faster.tsx:14]: Regarding `select.exists` I thought so too, but there's no `import select from 'select-dom';`

Comment (yakov116) [reply source/features/edit-comments-faster.tsx:14]: Yes

File: source/features/edit-comments-faster.tsx [hunk 3]
```diff
@@ -1,14 +1,27 @@
...
 import {observe} from 'selector-observer';
 import {PencilIcon} from '@primer/octicons-react';
 import * as pageDetect from 'github-url-detection';
 
 import features from '.';
 
+function canEditDiscussion(): boolean {
+	return select.exists(`
+	.current-user span[title^="You are the author"],
+	.current-user span[title^="You are a collaborator"],
```
Comment (yakov116) [inline source/features/edit-comments-faster.tsx:13]:
```suggestion
	.current-user span:is([title^="You are the author"], [title^="You are a collaborator"]),
```

File: source/features/edit-comments-faster.tsx [hunk 4]
```diff
@@ -1,14 +1,27 @@
...
 import onetime from 'onetime';
+import select from 'select-dom';
 import {observe} from 'selector-observer';
 import {PencilIcon} from '@primer/octicons-react';
 import * as pageDetect from 'github-url-detection';
 
 import features from '.';
 
+function canEditDiscussion(): boolean {
+	return select.exists(`
```
Comment (yakov116) [inline source/features/edit-comments-faster.tsx:11]:
```suggestion
	return pageDetect.isDiscussion() && select.exists(`
```

File: source/features/edit-comments-faster.tsx [hunk 5]
```diff
@@ -1,14 +1,27 @@
...
+
 function init(): void {
-	// Find editable comments first, then traverse to the correct position
-	observe('.js-comment.unminimized-comment .js-comment-update:not(.rgh-edit-comment)', {
+	let preSelector = '';
+	if (pageDetect.isDiscussion()) {
+		preSelector = canEditDiscussion() ? '' : '.current-user';
+	}
+
+	observe(preSelector + '.js-comment.unminimized-comment .js-comment-update:not(.rgh-edit-comment)', {
```
Comment (yakov116) [inline source/features/edit-comments-faster.tsx:24]:
```suggestion
	const preSelector = !pageDetect.isDiscussion() || canEditDiscussion() ? '' : '.current-user';

	observe(preSelector + '.js-comment.unminimized-comment .js-comment-update:not(.rgh-edit-comment)', {
```

Does this work?

Comment (darkred) [reply source/features/edit-comments-faster.tsx]: Yes, thank you.

File: source/features/edit-comments-faster.tsx (hunk 1 above)
Comment (darkred) [reply source/features/edit-comments-faster.tsx]: @fregante, @yakov116 
Is it working ok for you with issue #4400 ?

This PR in its current state only applies to Discussion pages,
so you shouldn't have problem.

**Comment by darkred** [comment]
Also, I made two corrections:

the `.current-user span:is([title^="You are the author"],` selector is irrelevant: 
it refers to: `You are the author of this discussion`.

Also the `[title^="You are a collaborator"]` should change to "You have been invited to"



So I changed the selectors to:

```
.current-user span:is([title^="You are a maintainer on this repository"], [title^="You have been invited to collaborate on"]),
```

**Review by yakov116 — APPROVED** [review]
LGTM

File: source/features/edit-comments-faster.tsx [hunk 6]
```diff
@@ -1,14 +1,22 @@
...
 import {observe} from 'selector-observer';
 import {PencilIcon} from '@primer/octicons-react';
 import * as pageDetect from 'github-url-detection';
 
 import features from '.';
 
+function canEditDiscussion(): boolean {
+	return pageDetect.isDiscussion() && select.exists(`
+	.current-user span:is([title^="You are a maintainer on this repository"], [title^="You have been invited to collaborate on"]),
+	button[aria-label="Edit discussion title"]
```
Comment (fregante) [inline source/features/edit-comments-faster.tsx:13]: Is this not enough? In what case is the other needed? You can use an array of selectors if necessary, and add comments on each selector (see other features for style)

Comment (darkred) [reply source/features/edit-comments-faster.tsx:13]: This is what you suggest, right?

```js
function canEditDiscussion(): boolean {
	return pageDetect.isDiscussion() && select.exists([
		'.current-user span[title^="You are a maintainer on this repository"]',  // You are the author of the repo
		'.current-user span[title^="You have been invited to collaborate on"]',  // You are a collaborator
		'button[aria-label="Edit discussion title"]' // You can edit the discussion title (being collaborator is not always enough)
	]);
}
```

_I agree that using array is easier to read, than using template literals <code>\`...\`</code> and `is()`._
But, I'd prefer @yakov116 to share whether he is ok with this change.

Comment (fregante) [reply source/features/edit-comments-faster.tsx:13]: > _combining the two with `:is()`_.

Both can be used, what I meant is that the 2 existing lines can be 2 selectors. `:is()` is unchanged.



> This is what you suggest, right?

The comments don't add much information, they just repeat the selector in English. What I mean is something like "This is for mainainers/collaborators" and "This is for xyz"

What I asked though is _why is the last selector alone not enough?_ What role:

- lets you edit every comment, BUT
- doesn't let you change the title

In my mind, if you can edit every comment, you can also edit the title.

Comment (darkred) [reply source/features/edit-comments-faster.tsx:13]: Please help me clarify this:

In [here](https://github.com/sindresorhus/refined-github/pull/4415#discussion_r640047844) you said this:

> However I'm not seeing #4400 at all
> [[screenshot](https://user-images.githubusercontent.com/1402241/119717057-0a299f00-be90-11eb-95ac-b2c4692391cf.png)]
> Probably because @cheap-glitch is a collaborator there but can't edit the comments, whereas I'm a stranger  
> `canEditDiscussion` needs to be created with this in mind.

Υou say that one can be a collaborator, but still not edit every comment.
This can happen where? In both Issues and Discussions? 

I'm asking because I have been invited as collaborator in https://github.com/tophf/mpiv and https://github.com/Mottie/GitHub-userscripts
and I can edit all Issue/PR/discussion comments in both repos.

---

If the above is true, i.e. that for some repos, a collaborator cannot edit every comment,
then, making `canEditDiscussion` rely solely on whether you can edit the title, is not reliable: 
you may edit the title, simply because you started the discussion, i.e. you are the author of the discussion.

So, I believe the code should change to the following:

```js
function canEditDiscussion(): boolean {
	return pageDetect.isDiscussion() && 
    ( select.exists('.current-user span[title^="You are a maintainer on this repository"') || 
    ( select.exists('.current-user span[title^="You have been invited to collaborate on"') &&
      select.exists('button[aria-label="Edit discussion title"]') );
}
```

Comment (fregante) [reply source/features/edit-comments-faster.tsx:13]: > > However I'm not seeing #4400 at all
> > [[screenshot](https://user-images.githubusercontent.com/1402241/119717057-0a299f00-be90-11eb-95ac-b2c4692391cf.png)]
> > Probably because @cheap-glitch is a collaborator there but can't edit the comments, whereas I'm a stranger  
> > `canEditDiscussion` needs to be created with this in mind.
> 
> Υou say that one can be a collaborator, but still not edit every comment.
> This can happen where? In both Issues and Discussions? 

That was complete guesswork. The only thing I said there is that I don't see the bug and I don't know why.

I'm here asking _you_ to verify it. We don't need code based on suppositions that nobody tested 😃

Comment (darkred) [reply source/features/edit-comments-faster.tsx:13]: I thought you actually noticed this somewhere.

So far I could only verify this in my own test repo, and in those two repos that I am collaborator.

For the sake of testing I made a test comment in https://github.com/streetcomplete/StreetComplete/discussions/2671#discussioncomment-801868
and didn't notice the issue:

<details>
<summary>screenshot:</summary>


</details>

&nbsp;
Please note that @FloEdelmann is a *member* of that organization ([screenshot](https://user-images.githubusercontent.com/723651/120079348-0da16e00-c0bc-11eb-87a4-a5bf487ea569.jpg)) whereas I am a stranger, 
so there's nothing more I can do in terms of testing.

Comment (darkred) [reply source/features/edit-comments-faster.tsx]: Update:
I noticed that the text in Discussions is different than in Issues and PRs:
it's `You have been invited to collaborate on` on Issues and PRs,
while it's `You are a collaborator on this repository` on Discussions.
I just corrected the selector.

I also removed the `'button[aria-label="Edit discussion title"]'`
because as I said above, is an unreliable criteria:
you may edit the title, simply because you started the discussion, i.e. you are the author of the discussion.

**Comment by matkoniecz** [comment]
Please, do not spam in unrelated repos. Create a test account and test repo.

If you want to follow github rules about no multiple accounts - ask your friend/parent/grandparent/sibling/neighbor to create Github account and test repository.

Spam like https://github.com/streetcomplete/StreetComplete/discussions/2671#discussioncomment-801868 is irritating and confusing.

**Comment by darkred** [comment]
I deleted that comment (I should have done it immediately), sorry about that.

**Comment by darkred** [comment]
To summarize my findings, regarding user account repositories:

- Collaborator:
  - In Issues/PRs: `You have been invited to collaborate on`
  - In Discussions: `You are a collaborator on this repository`

- Owner:
  - In Issues/PRs: `You the owner of this repository`
  - In Discussions: `You are a maintainer on this repository`

- ~'Author'~
  - ~In Issues/PRs/Discussions: `You the author of this issue/pull request/discussion`~

therefore checking whether title is editable is unsuitable as criteria.

&nbsp;
I have tested the PR in all kinds of discussions I could find (incl. being maintainer, collaborator, or just OP).

**Review by FloEdelmann — APPROVED** [review]

**Comment by yakov116** [comment]
@fregante do you think we can merge this before the next release?
