### PR TITLE
Fix `user-profile-follower-badge` position

### LINKED ISSUE #4388: `user-profile-follower-badge` is misplaced when there are "@"s in the user's bio
When there's no "@" in the bio, the "follows you" is in the correct place:

screenshot

When there are "@"s in the bio, the "follows you" is placed after the last "@":

screenshot

screenshot

### PR DESCRIPTION
**Pull request by yakov116**
Fixes #4388 

## Test URLs
https://github.com/wizardforcel

## Screenshot
Before
image

After

image

I also dropped the pre-refresh code

### CODE REVIEW

File: source/features/user-profile-follower-badge.tsx [hunk 1]
```diff
@@ -21,15 +21,7 @@ const doesUserFollow = cache.function(async (userA: string, userB: string): Prom
...
-		const newProfileElement = select('.js-profile-editable-area a:last-child');
-		if (newProfileElement) {
-			newProfileElement.after(<span className="text-gray color-text-secondary"> · Follows you</span>);
-		} else {
-			// Pre "Repository refresh" layout
-			select('.vcard-names-container:not(.is-placeholder)')!.after(
-				<div className="rgh-follower-badge">Follows you</div>
-			);
-		}
+		select('.js-profile-editable-area .octicon-star')!.closest('mb-3')!.append(<span className="text-gray color-text-secondary"> · Follows you</span>);
```
Comment (fregante) [inline source/features/user-profile-follower-badge.tsx:24]:
```suggestion
		select('.js-profile-editable-area .octicon-star')!.closest('mb-3')!.append(
			<span className="text-gray color-text-secondary"> · Follows you</span>
		);
```

**Review by fregante — APPROVED** [review]
Untested but LGTM
