### PR TITLE
Remove `copy-file` from Markdown view

### LINKED ISSUE #2957: `copy-file` appears on rendered markdown files (and fails)
There used to be a condition/events that made the Copy button appear only when showing the source code. 

1. Visit https://github.com/DrewML/GifHub/blob/master/LICENSE.md
2. Notice Copy button (it shouldn't be there)
3. Switch to see the source (it works now)

### PR DESCRIPTION
**Pull request by yakov116**
Fixes #2957 
Test on https://github.com/DrewML/GifHub/blob/master/LICENSE.md 
<!--

Thanks for contributing! 🍄

1. LINKED ISSUES:
   Does this PR close/fix an existing issue? Write something like `Closes #10`

2. TEST URLS:
   Add some test URLs

3. SCREENSHOT:
   Add a screenshot here if your PR makes visual changes

### CODE REVIEW

File: source/features/copy-file.tsx [hunk 1]
```diff
@@ -42,7 +42,7 @@ function removeButton(): void {
 function init(): void {
 	delegate('.rgh-copy-file', 'click', handleClick);
 
-	if (select.exists('.blob.instapaper_body')) {
+	if (select.exists('.blob.js-code-block-container')) {
```
Comment (fregante) [inline source/features/copy-file.tsx:45]: I'd prefer something more self-explanatory
```suggestion
	if (select.exists('.blob > .markdown-body')) {
```
