### PR TITLE
Fix broken patch/diff links on commit PRs. Fixes #104

### LINKED ISSUE #104: .patch and .diff links are not working from a PR commit
GitHub still supports the `/commit/<sha>.patch` and `/commit/<sha>.diff` URLs, but it doesn't support them on PR commits like https://github.com/sindresorhus/refined-github/pull/99/commits/24b1e2710a1c93f9ff02e35837629b93ee3ff4fa, it shows an inline 404 about not founding a commit range https://github.com/sindresorhus/refined-github/pull/99/commits/24b1e2710a1c93f9ff02e35837629b93ee3ff4fa.patch I guess this has something to do with `..` and `...` range operators in Git.

I consider this to be a bug caused by overlooking the patch and diff support from GitHub and I'll contact them about it, but we can still work around it by constructing the original commit URL (sometimes using the fork URL).

### PR DESCRIPTION
**Pull request by DrewML**
Note: Once #99 goes in, it would make sense to switch out the `prCommit` regex local to this function with the `isPRCommit` regex (the one that will be moving to the URL utils file shortly).

### CODE REVIEW

File: extension/content.js [hunk 1]
```diff
@@ -268,7 +268,11 @@ function linkifyIssuesInTitles() {
 }
 
 function addPatchDiffLinks() {
-	const commitUrl = location.href.replace(/\/$/, '');
+	let commitUrl = location.href.replace(/\/$/, '');
+	const prCommit = /\/pull\/\d+\/commits/;
+	if (prCommit.test(commitUrl)) {
+		commitUrl = commitUrl.replace(prCommit, '/commit');
```
Comment (hkdobrev) [inline extension/content.js]: This check does not handle forks well. I'm not sure if it's easy to support forks in this scenario though.

Comment (DrewML) [inline extension/content.js]: I figured it wouldn't be this easy :) Do you have an example link to a page where it breaks down?

Comment (hkdobrev) [inline extension/content.js]: Hmm, actually when checking it out, it seems GitHub copies the commits in the base repo so it's working properly even with PRs from forks.

**Comment by hkdobrev** [comment]
LGTM :dizzy:

**Comment by sindresorhus** [comment]
>  it would make sense to switch out the prCommit regex local to this function with the isPRCommit regex

#99 landed. Can you do this?

**Comment by DrewML** [comment]
No problem - will push an update after work tonight.

**Comment by DrewML** [comment]
On second thought, I'm going to sit on this until #123 goes in (it's pretty small), and then I'll make the update to consume the new page-detection module.

**Comment by hkdobrev** [comment]
> On second thought, I'm going to sit on this until #123 goes in (it's pretty small), and then I'll make the update to consume the new page-detection module.

Hehe, I thought I'll update this code in #123 after this is merged as this is a bugfix and #123 is changing more things and needs to be more thoroughly tested.

**Comment by DrewML** [comment]
@hkdobrev Cool, that works for me. Wasn't going to throw the work over the fence to you, but now I will :)

**Comment by DrewML** [comment]
Update pushed.

**Comment by hkdobrev** [comment]
LGTM :shipit:
