### PR TITLE
Fix delete fork button for merged PRs

### LINKED ISSUE #298: Delete fork link is broken
The delete fork link is going to delete https://github.com/tenant/settings. It looks like it's got to do with this parsing here https://github.com/sindresorhus/refined-github/blob/master/extension/content.js#L131. Maybe the UI changed for Github?

### PR DESCRIPTION
**Pull request by paulmolluzzo**
This fixes #298.

I changed the method of making the fork path to use an `attr` found in the DOM that has the fork's user and repo name. It seems like this is appropriate for creating the path to the settings for the fork, and the existing tests (not the original repo, is merged, etc.) remained intact.

### CODE REVIEW

File: extension/content.js [hunk 1]
```diff
@@ -128,7 +128,7 @@ function addDeleteForkLink() {
 
 	if ($postMergeContainer.length > 0) {
 		const $postMergeDescription = $postMergeContainer.find('.merge-branch-description');
-		const forkPath = $postMergeContainer.attr('data-channel').split(':')[0];
+		const forkPath = `${getUsername()}/${repoName}`;
```
Comment (hkdobrev) [inline extension/content.js]: That's nice, but would it work if your fork is not in your personal account?

Comment (hkdobrev) [inline extension/content.js]: @paulmolluzzo I've specifically meant the following case:

You have a personal account **`A`** and you are a part of an organisation **`O`**. You have forked a repo **`B/C`** not to your personal account, but to your organisation **`O`**. So the correct forked repo URL is **`O/C`**. However with that change the extension would still generate **`A/C`** for the forked repo URL.

I don't usually use the GitHub functionality to change accounts on the dashboard, but I sometimes fork repositories to an organisation account when for example I'm doing open-source PR at work and I'm sharing the fork with colleagues.

P.S. Your scenarios are interesting, but just checked and if you change account on the GitHub dashboard that doesn't change account across the whole GitHub, but just the dashboard so I think the scenario above is the only one which we should concerns ourselves with about organisations.

P.P.S. You can create an organisation for free if you want to test things.

Comment (hkdobrev) [inline extension/content.js]: Another completely different case here is renamed forks. You can fork a repo, rename the fork and it would still be a fork of the original. Example: https://github.com/hkdobrev/hkdobrev.github.io

I doubt people who have renamed a fork would want to have a delete button as they probably renamed it in order to keep it. Although we shouldn't generate 404s if possible I guess.

Keep in mind this is a rare case and shouldn't be addressed IMHO unless easy enough.

Comment (paulmolluzzo) [inline extension/content.js]: Thanks, I had a feeling you were thinking this, and really we need the "source" to make the URL. Maybe we can do it from the linkified branches?

Comment (paulmolluzzo) [inline extension/content.js]: Pushed a fix that now uses the original branch URL provided by GH in the DOM. I think this solves the possible scenario of accounts `A`, `B`, and organization `O` since it doesn't rely on you being logged in to any particular account.

Comment (hkdobrev) [inline extension/content.js]: I've just found out I have a case for this: https://github.com/kurlltd/silex-doctrine-migrations-provider/pull/8

screen shot 2016-10-24 at 23 10 46

The actual owner of the fork is right there in the DOM with the following HTML structure:

``` html
<span class="commit-ref current-branch css-truncate user-select-contain expandable head-ref" title="clippings/silex-doctrine-migrations-provider:composer-type">
    <span class="css-truncate-target user">clippings</span>:
    <span class="css-truncate-target">composer-type</span>
</span>
```
We are wrapping that span with a link when linkifying the branch.

> Maybe we can do it from the linkified branches?

I guess that's what you mean and we can easily use it, right?

Do you need help with a reproducible case? If you want to do this and update the PR, please ping me so I can test it out as well.

Comment (hkdobrev) [inline extension/content.js]: Oh, you've just updated it 😆  Testing now.

**Comment by paulmolluzzo** [comment]
@hkdobrev better as "Fix delete fork button for merged PRs"?

**Comment by hkdobrev** [comment]
@paulmolluzzo I meant the PR description body, not the title, but in any case, this PR is good to merge 😺
