### PR TITLE
Reaction avatars bug fixes 

### LINKED ISSUE #233: Reaction Avatars should update on "remote" changes
If you're on an issue/PR and there are reactions to comments the avatars will disappear if someone else reacts. There should be a Mutation Observer or something to track those elements and re-add the avatars on an update.

It's actually hiding the avatars, so _something_ is happening.

### PR DESCRIPTION
**Pull request by bfred-it**
Fixes #233 (oldest bug open)

And solves the two ugly problems you see here: 

wrapping + duplicate tooltip

### CODE REVIEW

File: source/libs/on-new-comments.js [hunk 1]
```diff
@@ -0,0 +1,35 @@
+import once from 'onetime';
```
Comment (bfred-it) [inline source/libs/on-new-comments.js]: This file is not currently used for this feature, but it's still valid for generic  comment features except this one.

**Comment by sindresorhus** [comment]
> (oldest bug open)

🎉🙌🎉
