### PR TITLE
Fix `more-dropdown` on GHE

### LINKED ISSUE #3953: `more-dropdown`: Cannot read property 'parentElement' of undefined
Refined GitHub version: 21.2.1
Chrome version: 88.0.4324.96 (macOS, x86_64)
GitHub version: GitHub Enterprise Server 2.22.3

Looks very similar to #3811, but with `undefined` rather than `null`:
```
❌ Refined GitHub → more-dropdown → TypeError: Cannot read property 'parentElement' of undefined
    at onlyShowInDropdown (VM104 refined-github.js:3098)
    at init (VM104 refined-github.js:3115)
    at async runFeature (VM104 refined-github.js:2091)
    at async setupPageLoad (VM104 refined-github.js:2099) 
```

I can reproduce this on any page within a repo on GitHub Enterprise, but not on GitHub.com, so I unfortunately can't provide a URL.

<details>
<summary>Full console output:</summary>

```
15:05:06.578 Navigated to https://<ghe>/<org>/<repo>

15:05:06.681 VM109 refined-github.js:2081 Refined GitHub has been loaded twice. If you didn’t install the developer version, this may be a bug. Please report it to: https://github.com/sindresorhus/refined-github/issues/565
  (anonymous) @ VM109 refined-github.js:2081
  async function (async)
  (anonymous) @ VM109 refined-github.js:2076
  (anonymous) @ VM109 refined-github.js:2075
  (anonymous) @ VM109 refined-github.js:8899
  (anonymous) @ VM109 refined-github.js:8900

15:05:06.720 refined-github.js:2081 Refined GitHub has been loaded twice. If you didn’t install the developer version, this may be a bug. Please report it to: https://github.com/sindresorhus/refined-github/issues/565
  (anonymous) @ refined-github.js:2081
  async function (async)
  (anonymous) @ refined-github.js:2076
  (anonymous) @ refined-github.js:2075
  (anonymous) @ refined-github.js:8899
  (anonymous) @ refined-github.js:8900

15:05:06.755 VM104 refined-github.js:2073 ❌ Refined GitHub → more-dropdown → TypeError: Cannot read property 'parentElement' of undefined
    at onlyShowInDropdown (VM104 refined-github.js:3098)
    at init (VM104 refined-github.js:3115)
    at async runFeature (VM104 refined-github.js:2091)
    at async setupPageLoad (VM104 refined-github.js:2099) 
  Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Cannot%20read%20property%20'parentElement'%20of%20undefined

  Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60more-dropdown%60%3A%20Cannot%20read%20property%20'parentElement'%20of%20undefined
		
  logError @ VM104 refined-github.js:2073
  runFeature @ VM104 refined-github.js:2093
  async function (async)
  runFeature @ VM104 refined-github.js:2091
  setupPageLoad @ VM104 refined-github.js:2099
  add @ VM104 refined-github.js:2133
  async function (async)
  add @ VM104 refined-github.js:2118
  (anonymous) @ VM104 refined-github.js:3105
  (anonymous) @ VM104 refined-github.js:8899
  (anonymous) @ VM104 refined-github.js:8900

15:05:06.866 VM104 refined-github.js:2073 ℹ️ Refined GitHub → latest-tag-button → Personal token required for this feature
15:05:06.868 VM104 refined-github.js:2073 ℹ️ Refined GitHub → repo-age → Personal token required for this feature
15:05:06.868 VM104 refined-github.js:2073 ℹ️ Refined GitHub → bugs-tab → Personal token required for this feature
15:05:06.896 VM104 refined-github.js:2073 ❌ Refined GitHub → cleanup-repo-filelist-actions → TypeError: Cannot read property 'replaceWith' of null
    at init (VM104 refined-github.js:7575)
    at runFeature (VM104 refined-github.js:2091)
    at setupPageLoad (VM104 refined-github.js:2099)
    at VM104 refined-github.js:2132 
  Search issue: https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Cannot%20read%20property%20'replaceWith'%20of%20null

  Open an issue: https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60cleanup-repo-filelist-actions%60%3A%20Cannot%20read%20property%20'replaceWith'%20of%20null
		
  logError @ VM104 refined-github.js:2073
  runFeature @ VM104 refined-github.js:2093
  setupPageLoad @ VM104 refined-github.js:2099
  (anonymous) @ VM104 refined-github.js:2132
  async function (async)
  (anonymous) @ VM104 refined-github.js:2132
  add @ VM104 refined-github.js:2133
  async function (async)
  add @ VM104 refined-github.js:2118
  (anonymous) @ VM104 refined-github.js:7564
  (anonymous) @ VM104 refined-github.js:8899
  (anonymous) @ VM104 refined-github.js:8900

15:05:07.128 vendor-0d444107.js:135 Fetch finished loading: GET "https://<ghe>/<org>/<repo>/show_partial?partial=tree%2Frecently_touched_branches_list".
  window.IncludeFragmentElement.fetch @ vendor-0d444107.js:135
  (anonymous) @ vendor-0d444107.js:135
  Promise.then (async)
  load @ vendor-0d444107.js:135
  ae @ vendor-0d444107.js:135
  oe @ vendor-0d444107.js:135
  connectedCallback @ vendor-0d444107.js:135
  execute @ vendor-0d444107.js:135
  (anonymous) @ environment-bootstrap-0b18da31.js:1
  Promise.then (async)
  register @ environment-bootstrap-0b18da31.js:1
  (anonymous) @ vendor-0d444107.js:1

15:05:07.556 VM104 refined-github.js:3985 Fetch finished loading: GET "https://<ghe>/<org>/<repo>/commits".
  (anonymous) @ VM104 refined-github.js:3985
  (anonymous) @ VM104 refined-github.js:467
  (anonymous) @ VM104 refined-github.js:4683
  (anonymous) @ VM104 refined-github.js:659
  init @ VM104 refined-github.js:4697
  runFeature @ VM104 refined-github.js:2091
  setupPageLoad @ VM104 refined-github.js:2099
  add @ VM104 refined-github.js:2133
  async function (async)
  add @ VM104 refined-github.js:2118
  (anonymous) @ VM104 refined-github.js:4692
  (anonymous) @ VM104 refined-github.js:8899
  (anonymous) @ VM104 refined-github.js:8900
```
</details>

### PR DESCRIPTION
**Pull request by cheap-glitch**
Thanks for contributing! 🍄

1. LINKED ISSUES: Fixes #3953 

2. TEST URLS: Any repo page. The "Security" and "Insights" tabs should be moved to the dropdown.

My guess is that the bug is caused by the absence of the "Security" tab when doing:
```typescript
onlyShowInDropdown('security-tab');
onlyShowInDropdown('insights-tab');
```
I can't test this on GHE, but checking for the existence of the tab element should fix this.

### CODE REVIEW

**Comment by fregante** [comment]
Thanks, this however silences errors for everyone. If the security tab doesn't existing on GHE, I'd rather see a `if !isGHE, onlyShowInDropdown('security-tab')`

**Comment by busches** [comment]
I do not have access to this version of GHE to confirm. Hopefully @occr or maybe @mrbusche can test.

**Comment by cheap-glitch** [comment]
> Thanks, this however silences errors for everyone. If the security tab doesn't existing on GHE, I'd rather see a `if !isGHE, onlyShowInDropdown('security-tab')`

Is the "Security" tab never present on GHE? If it's only missing sometimes, how about:
```typescript
if (!tabItem && isGHE) {
	return;
}
```

**Comment by orrc** [comment]
The last couple of versions of the [Enterprise docs][0] do mention the "Security tab" as being a thing — it's just not something that appears in any of the many repos I've checked on the one GHE install I have access to.

In any case, I tested this PR and the `more-dropdown` error is no longer present. 👍

[0]:https://docs.github.com/en/enterprise-server@2.22/github/managing-security-vulnerabilities/configuring-notifications-for-vulnerable-dependencies

File: source/features/more-dropdown.tsx [hunk 1]
```diff
@@ -38,7 +38,12 @@ export function createDropdownItem(label: string, url: string, attributes?: Reco
 }
 
 function onlyShowInDropdown(id: string): void {
-	select(`[data-tab-item$="${id}"]`)!.parentElement!.remove();
+	const tabItem = select(`[data-tab-item$="${id}"]`);
+	if (!tabItem && pageDetect.isEnterprise()) {
```
Comment (yakov116) [inline source/features/more-dropdown.tsx:42]: @fregante comment? or no need?

**Comment by mrbusche** [comment]
On GHE 2.22.6 I'm not seeing the Security tab with or without admin rights.
image

File: source/features/more-dropdown.tsx (hunk 1 above)
Comment (fregante) [reply source/features/more-dropdown.tsx:42]: Yeah, it’s worth pointing to this PR
```suggestion
	if (!tabItem && pageDetect.isEnterprise()) { // #3962
```

Comment (fregante) [reply source/features/more-dropdown.tsx:42]: Can be merged after this

Comment (yakov116) [reply source/features/more-dropdown.tsx:42]: I think you meant

```suggestion
	if (!tabItem && pageDetect.isEnterprise()) { // GHE might not have the Security tab #3962
```
