### PR TITLE
Fix `clean-repo-filelist-actions` feature

### LINKED ISSUE #4682: `clean-repo-filelist-actions` is partially broken
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

The `Code` text is no longer hidden, see screenshot below.

### Screenshot

image

### Console errors

_No response_

### Example URL

https://github.com/sindresorhus/refined-github

### Browser(s) used

Chrome

### PR DESCRIPTION
**Pull request by kidonng**
Fix #4682

## Test URLs

https://github.com/sindresorhus/refined-github

## Screenshot

image

### CODE REVIEW

**Comment by fregante** [comment]
Can you add a date to drop the download icon selector? Like November

**Comment by kidonng** [comment]
I get it, you are asking for a unique screenshot. I was being lazy 😄

File: source/features/clean-repo-filelist-actions.tsx [hunk 1]
```diff
@@ -38,12 +38,13 @@ function init(): void {
...
-			if (downloadIcon) {
+			// Remove `.octicon-download` in November
+			const codeIcon = select('get-repo :is(.octicon-code, .octicon-download)');
+			if (codeIcon) {
 				// Remove "Code" text next to it
-				downloadIcon.nextSibling!.remove();
+				codeIcon.nextSibling!.remove();
 
-				addTooltipToSummary(downloadIcon, 'Clone, open or download');
+				addTooltipToSummary(codeIcon, 'Clone, open or download');
```
Comment (fregante) [inline source/features/clean-repo-filelist-actions.tsx:47]:
```js
addTooltipToSummary(codeIcon, codeIcon.nextSibling!.textContent);

// Remove "Code" text next to it
codeIcon.nextSibling!.remove();
```

Comment (fregante) [reply source/features/clean-repo-filelist-actions.tsx:47]: 👎 it's better as is. "Code" isn't very useful as a tooltip

Comment (kidonng) [reply source/features/clean-repo-filelist-actions.tsx:47]: I was about to reply roughly the same thing. Also doesn't make sense for me to use `textContent` instead of a literal `"Code”`.
