### PR TITLE
Check for multiple related issues in `deep-reblame`

### LINKED ISSUE #4440: `deep-reblame` doesn't work if there are multiple unrelated linked issues
1. Visit https://github.com/pixiebrix/pixiebrix-extension/blame/69a0e85c03f57e094591865b5dcf0632c4c9e26f/browsers/chrome/webpack/webpack.dev.js#L101
2. alt-click reblame icon
3. "The PR linked in the title didn’t create this commit"

This is because the commit title also includes a link to an issue. This is because our code only looks for the first link:

https://github.com/sindresorhus/refined-github/blob/addd5ab1bce675fbebfbd373569eb2333b49b95e/source/features/deep-reblame.tsx#L66

We can probably fix this by using a more specific `[data-hovercard-type="pull_request"]`  instead.

In the PR: Please include a gif of this successfully working on that page

### PR DESCRIPTION
**Pull request by yakov116**
Fixes #4440 
## Test URLs
1. Visit https://github.com/pixiebrix/pixiebrix-extension/blame/69a0e85c03f57e094591865b5dcf0632c4c9e26f/browsers/chrome/webpack/webpack.dev.js#L101
2. alt-click reblame icon

Related PR in commit title: it should "enter" it https://github.com/sindresorhus/refined-github/blame/b5497da33a6c5b99eb518ecc266881780bc11877/contributing.md#L7

Unrelated PR in commit title: it should `alert()` https://github.com/sindresorhus/refined-github/blame/d1e27cb34f18b9d5d57fdbf853e5b15c3a660d85/source/features/deep-reblame.tsx#L67

Renamed file: it should `alert()` https://github.com/sindresorhus/refined-github/blame/fad67fb8d8fcf608601c9b8ae1b5f12337cbccce/source/options.html#L1

## Screenshot
Video_2021-06-03_094736

### CODE REVIEW

**Comment by yakov116** [comment]
Marked as draft since I want to check the commit title.

**Comment by yakov116** [comment]
@fregante I cannot find where we discussed it but we did not add the commit title as anyone can type what every they want.

File: source/features/deep-reblame.tsx [hunk 1]
```diff
@@ -63,15 +63,19 @@ async function redirectToBlameCommit(event: delegate.Event<MouseEvent, HTMLAncho
 	blameElement.blur(); // Hide tooltip after click, it’s shown on :focus
 
 	const blameHunk = blameElement.closest('.blame-hunk')!;
-	const prNumber = looseParseInt(select('.issue-link', blameHunk)!);
+	const prNumbers = [];
+	for (const pr of select.all('.issue-link', blameHunk)) {
+		prNumbers.push(looseParseInt(pr));
+	}
```
Comment (fregante) [inline source/features/deep-reblame.tsx:69]: I think you can use `select.all().map()` instead of the for loop

**Comment by fregante** [comment]
I’m not sure I understand your last comment. Which commit title? We’re already getting the issue links from the commit title, right?

**Comment by yakov116** [comment]
> I’m not sure I understand your last comment. Which commit title? We’re already getting the issue links from the commit title, right?
There is the commit title and then there is the pull request title.

You might be right. Let me double check what I did here later. I wrote this in under 3 min.

**Comment by yakov116** [comment]
Please ignore my last comment

**Review by fregante — APPROVED** [review]
Untested but code LGTM
