### PR TITLE
Fix keyboard shortcuts on comment fields

### LINKED ISSUE #1252: Escape key canceling comments is conflicting with closing the emoji menu
I'm talking about this code :
https://github.com/sindresorhus/refined-github/blob/master/source/features/add-keyboard-shortcuts-to-comment-fields.js#L42-L50

The problem is that when you type a `:` after a ` `, GitHub opens the emoji menus, and the most obvious way to close it is with the `esc` key, but the `esc` key will close the comment. In some cases (but not all), you get a confirmation window, so you actually don't lose what you've typed. In some cases you don't. This makes this feature actually really painful.

This problem happens a lot when you write comments using languages that require a ` ` before `:`, like French.

### PR DESCRIPTION
**Pull request by notlmn**
Fixes #1252.

* Don't do **anything** if the selector box is open (separated this so that it may possibly useful for #1003)
* Add support for hiding "edit comment" box
* On 'Escape', if there is a cancel button then close the view, else blur the field

### CODE REVIEW

**Comment by notlmn** [comment]
The recent version of XO has added more rules that now fails on previous files, and now Travis build fails.

Should I fix the linting errors in this PR or a separate one?

**Comment by busches** [comment]
Separate.

**Comment by notlmn** [comment]
Rebased `master` onto this branch, now the tests pass!

File: source/features/add-keyboard-shortcuts-to-comment-fields.js [hunk 1]
```diff
@@ -40,16 +41,20 @@ export default function () {
...
+			// Cancel buttons have different classes for inline comments and editable comments
+			const cancelButton = select(`
+				.js-hide-inline-comment-form,
+				.js-comment-cancel-button
+			`, field.form);
 
-			// Cancel comment if inline, blur the field if it's a regular comment
-			if (field.value === '') {
+			// Cancel if there is a button, else blur the field
+			if (cancelButton) {
```
Comment (bfred-it) [inline source/features/add-keyboard-shortcuts-to-comment-fields.js]: Consideration: It's missing `field.value === ''` but I think it wasn't necessary because:

- `esc` here will be exactly like clicking the `Cancel` button
- If the field is not empty, the user should be asked for confirmation with `add-confirmation-to-comment-cancellation`

**Comment by bfred-it** [comment]
Thanks @notlmn! :)

File: source/features/add-keyboard-shortcuts-to-comment-fields.js (hunk 1 above)
Comment (notlmn) [reply source/features/add-keyboard-shortcuts-to-comment-fields.js]: For now, I've found these inline fields to be "edit comment field" and "add inline comment", both of which check if the input is empty before hiding themselves.
