### PR TITLE
Lint and minor console errors fixes

### LINKED ISSUE #2849: Console Errors
When adding a ? in a comment box
https://github.com/sindresorhus/refined-github/blob/767a210d4d5f9e4b58598bed95f218f57ebfe296/source/features/improve-shortcut-help.tsx#L49
test on https://github.com/sindresorhus/refined-github/commit/cb8de12eb680475024c21d5586aa31a232493c73 add a `?` in the comment box
```console
content.js:4679 Uncaught TypeError: Failed to execute 'observe' on 'MutationObserver': parameter 1 is not of type 'Node'.
    at HTMLDocument.<anonymous> (content.js:4679)
```

Pr-braches fails if the user is 👻 `@ghost`
test on https://github.com/drop-ice/dear-github-2.0/pulls?q=is%3Apr+sort%3Aupdated-desc+is%3Aclosed
```console
content.js:12365 ❌ Refined GitHub: feature `pr-branches`

 TypeError: Cannot read property 'login' of null
    at normalizeBranchInfo (content.js:7195)
    at pr_branches_init (content.js:7247)
    at async features_run (content.js:2923) 

Search for open issues:
https://github.com/sindresorhus/refined-github/issues?q=is%3Aissue+Cannot%20read%20property%20'login'%20of%20null

or open a new one:
https://github.com/sindresorhus/refined-github/issues/new?labels=bug&template=bug_report.md&title=%60pr-branches%60%3A%20Cannot%20read%20property%20'login'%20of%20null
```

### PR DESCRIPTION
**Pull request by yakov116**
Idea came from https://github.com/sindresorhus/refined-github/pull/2858#discussion_r388836596
Fixes #2849

<!-- 

Thanks for contributing! 🍄

1. LINKED ISSUES:
   Does this PR close/fix an existing issue? Write something like `Closes #10`

2. TEST URLS:
   Add some test URLs

3. SCREENSHOT:
   Add a screenshot here if your PR makes visual changes

### CODE REVIEW

File: source/features/improve-shortcut-help.tsx [hunk 1]
```diff
@@ -45,8 +45,8 @@ const observer = new MutationObserver(([{target}]) => {
 });
 
 function init(): void {
-	document.addEventListener('keypress', ({key}) => {
-		if (key === '?') {
+	document.addEventListener('keypress', ({key, target}) => {
+		if (key === '?' && (target as HTMLTextAreaElement).type !== 'textarea') {
```
Comment (fregante) [inline source/features/improve-shortcut-help.tsx]: I think this isn't safe enough, the target could also be `input`. GitHub has other conditions this might not meet.

To avoid the error specifically, this could be:
```suggestion
		if (key !== '?' || target instanceof HTMLTextAreaElement || target instanceof HTMLInputElement) {
			return;
		}
```

and then

```js
const modal = select('body > details > details-dialog');
if (modal) {
 			observer.observe(modal, {childList: true});
}
```

Comment (fregante) [reply source/features/improve-shortcut-help.tsx]: 🤔

Comment (yakov116) [reply source/features/improve-shortcut-help.tsx]: ohh... but it works? Im confused

File: source/features/improve-shortcut-help.tsx [hunk 2]
```diff
@@ -45,11 +45,14 @@ const observer = new MutationObserver(([{target}]) => {
...
-			observer.observe(select('body > details > details-dialog')!, {childList: true});
+	document.addEventListener('keypress', ({key, target}) => {
+		if (key !== '?' || target instanceof HTMLTextAreaElement || target instanceof HTMLInputElement) {
+			return;
 		}
-	});
+
+		observer.observe(select('body > details > details-dialog')!, {childList: true});
+	}
+	);
```
Comment (fregante) [inline source/features/improve-shortcut-help.tsx]:
```suggestion
	});
```

**Comment by yakov116** [comment]
i am very lost. @fregante take over from here (I'm babysitting and I am not Mom, so cant multi task 😆 )

File: source/features/improve-shortcut-help.tsx (hunk 1 above)
Comment (fregante) [reply source/features/improve-shortcut-help.tsx]: The intent of this listener is to catch the opening of `details-dialog`. Just because the key `?` was pressed outside fields, it doesn't mean that GitHub opened it. They have more conditions.

This is what I meant with:

> I think this isn't safe enough, [...] GitHub has other conditions this might not meet.

File: source/features/improve-shortcut-help.tsx [hunk 3]
```diff
@@ -45,10 +45,12 @@ const observer = new MutationObserver(([{target}]) => {
...
 function init(): void {
-	document.addEventListener('keypress', ({key}) => {
-		if (key === '?') {
-			observer.observe(select('body > details > details-dialog')!, {childList: true});
+	document.addEventListener('keypress', ({key, target}) => {
+		if (key !== '?' || target instanceof HTMLTextAreaElement || target instanceof HTMLInputElement) {
+			return;
 		}
+
+		observer.observe(select('body > details > details-dialog')!, {childList: true});
```
Comment (fregante) [inline source/features/improve-shortcut-help.tsx]:
```suggestion
		const modal = select('body > details > details-dialog');
		if (modal) {
			observer.observe(modal, {childList: true});
		}
```
