### PR TITLE
Fix `close-out-of-view-modals` conflict with GitHub Actions UI

### LINKED ISSUE #2328: Cannot click 're-run all checks' on Actions page
If you're on the latest beta of GitHub Actions, there's a drop-down for re-running all checks that you can't click.

I can confirm that it works fine on Firefox and in Chrome after I've disabled the extension.

Example URL — https://github.com/paambaati/websight/pull/10/checks?check_run_id=193115347

Screenshot of the dropdown in question (from Firefox)

Screenshot 2019-08-14 at 2 41 10 PM

**CSS selector**
```
details.dropdown:nth-child(1) > summary:nth-child(1)
```

**Markup**
```html
<div>
          <details class="dropdown details-reset details-overlay d-inline-block ml-4 mt-n1" open="">
            <summary class="btn btn-sm" aria-haspopup="true">
              <svg></svg>
              Re-run checks
              <div class="dropdown-caret"></div>
            </summary>

            <template id="js-check-suite-rerequest-form-success">
              <div class="flash flash-full flash-notice">
  <div class="container">
    <button class="flash-close js-flash-close" type="button" aria-label="Dismiss this message">
      <svg></svg>
    </button>
    
                You have successfully requested checks from GitHub Actions.

  </div>
</div>
            </template>

            <template id="js-check-suite-rerequest-form-error">
              <div class="flash flash-full flash-error">
  <div class="container">
    <button class="flash-close js-flash-close" type="button" aria-label="Dismiss this message">
      <svg></svg>
    </button>
    
                There was a problem requesting checks from GitHub Actions.

  </div>
</div>
            </template>

            <ul class="dropdown-menu dropdown-menu-sw" style="width: 170px">
              <li>
              </li>
              <li>
                    <input type="hidden" name="only_failed_check_runs" value="false">
                    <button class="dropdown-item btn-link" type="submit">
                      Re-run all checks
                    </button>
</form>              </li>
            </ul>
          </details>

    </div>
```

### PR DESCRIPTION
**Pull request by notlmn**
Fixes #2328.

As mentioned in https://github.com/sindresorhus/refined-github/issues/2328#issuecomment-522060316, the `details` element can contain content after its `summary` element that is not visible to the user. What we actually need is the `.dropdown-menu` item, which is targeted using the change in this PR.

## Test

- Test on user dropdown/create repo dropdown available on every GH page header.
- If you have access to GH Actions, this can be tested on a PR which has one or more failed checks, and you have access to re-run checks.

### CODE REVIEW

File: source/features/close-out-of-view-modals.tsx [hunk 1]
```diff
@@ -13,7 +14,7 @@ function init(): void {
 	// so the selector is inverted
 	delegate('.details-overlay:not([open]) > summary', 'click', event => {
 		// What comes after <summary> is the dropdown
-		observer.observe(event.delegateTarget.nextElementSibling!);
+		observer.observe(select('.dropdown-menu', event.delegateTarget.parentElement!)!);
```
Comment (fregante) [inline source/features/close-out-of-view-modals.tsx]: I don’t like mixing `select` with other dom traversal properties on the same line, it makes it hard to follow. Also you can use `({delegateTarget})` as a parameter to shorten the line further
```suggestion
		observer.observe(delegateTarget.parentElement!.querySelector('dropdown-menu')!);
```

File: source/features/close-out-of-view-modals.tsx [hunk 2]
```diff
@@ -1,4 +1,5 @@
 import delegate from 'delegate-it';
+import select from 'select-dom';
```
Comment (fregante) [inline source/features/close-out-of-view-modals.tsx]:
```suggestion
```
