### PR TITLE
Fix `restore-file` for deleted files in forks

### LINKED ISSUE #3417: `restore-file` can't restore deleted files in forks
> I wasn't able to undo the deleted file, the console reported this 404:
> 
> ```
> https://github.com/sindresorhus/refined-github/new/linkify-code?filename=source/features/format-conversation-titles.tsx
> ```
> 
> Screen Shot 2020-07-30 at 12 48 58
> 
> _Originally posted by @fregante in https://github.com/sindresorhus/refined-github/pull/3409#issuecomment-666318532_

This is probably because that 404 URL should be this instead:

```diff
- https://github.com/sindresorhus/refined-github/new/linkify-code?filename=source/features/format-conversation-titles.tsx
+ https://github.com/kidonng/refined-github/new/linkify-code?filename=source/features/format-conversation-titles.tsx
```

### PR DESCRIPTION
**Pull request by yakov116**
1. LINKED ISSUES:
   Fixes #3417 

2. TEST URLS:
   This PR

3. SCREENSHOT:
	None

### CODE REVIEW

File: source/features/restore-file.tsx [hunk 1]
```diff
@@ -58,7 +58,8 @@ async function commitFileContent(menuItem: Element, content: string, filePath: s
 	// Check if file was deleted by PR
 	if (menuItem.closest('[data-file-deleted="true"]')) {
 		menuItem.textContent = 'Undeleting…';
-		pathname = `/${getRepoURL()}/new/${getCurrentBranch()}?filename=` + filePath;
+		const [, user, repository] = select<HTMLAnchorElement>('.commit-ref.head-ref a')!.pathname.split('/', 3);
+		pathname = `${[user, repository, 'new', getCurrentBranch()].join('/')}?filename=${filePath}`;
```
Comment (fregante) [inline source/features/restore-file.tsx:62]:
```suggestion
		pathname = `/${user}/${repository}/new/${getCurrentBranch()}?filename=${filePath}`;
```

**Comment by fregante** [comment]
It worked! https://github.com/sindresorhus/refined-github/pull/3409#ref-issue-669171349
