### PR TITLE
Meta: Fix `rgh-feature-descriptions` feature

### LINKED ISSUE #4815: `rgh-feature-descriptions` is broken
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

Again! It seems Github removed both `.hx_commit-tease` and `include-fragment.commit-loader`. The closest other one I could find is `#blob_contributors_box`.

### Screenshot

image

### Console errors

```shell
❌ rgh-feature-descriptions 21.9.18 → TypeError: undefined has no properties
    init rgh-feature-descriptions.tsx:98
index.tsx:57:9
```

### Example URL

https://github.com/sindresorhus/refined-github/blob/main/source/features/batch-mark-files-as-viewed.tsx

### Browser(s) used

Firefox

### PR DESCRIPTION
**Pull request by gamemaker1**
Changes the selector to select the commit box to `.Box-header.Details`, as suggested in https://github.com/sindresorhus/refined-github/issues/4815#issuecomment-927072107.

Closes #4815 if merged.

### CODE REVIEW

File: source/features/rgh-feature-descriptions.tsx [hunk 1]
```diff
@@ -13,7 +13,7 @@ async function init(): Promise<void | false> {
 
 	const conversationsUrl = '/sindresorhus/refined-github/issues?q=' + encodeURIComponent(`"${feature.id}" sort:updated-desc`);
 
-	const commitInfoBox = (await elementReady('.hx_commit-tease, include-fragment.commit-loader'))!.parentElement!;
+	const commitInfoBox = (await elementReady('.Box-header.Details, include-fragment.commit-loader'))!.parentElement!;
```
Comment (gamemaker1) [inline source/features/rgh-feature-descriptions.tsx:16]: Should we drop `include-fragment.commit-loader`?

Comment (kidonng) [reply source/features/rgh-feature-descriptions.tsx:16]: > `include-fragment.commit-loader` is needed according to [`2683e30` (#3852)](https://github.com/sindresorhus/refined-github/pull/3852/commits/2683e300976cacbbb71eb219347cb82aa964616b).

**Comment by fregante** [comment]
If they're cross-compatible, let's keep the 3 selectors so we don't have to go back and forth for now. Also it's best to use a selector array with a comment after each selector

**Comment by gamemaker1** [comment]
> ... selector array with a comment after each selector

`elementReady` doesn't seem to accept an array. Anything I'm missing?

**Comment by fregante** [comment]
> > ... selector array with a comment after each selector
> 
> `elementReady` doesn't seem to accept an array. Anything I'm missing?

['a', 'b'].join(',')

**Comment by fregante** [comment]
I went back to look at the old PR: The selector was only broken back then because they had dropped the `--blue` class, but was otherwise valid as a generic "Box" selector. In short, the `hx` class was never needed.
