### PR TITLE
Fix some console errors

### LINKED ISSUE #2128: Console Errors
Any Password Page

```
❌ more-dropdown
content.js:2111 TypeError: Cannot read property 'append' of null
    at appendBefore (content.js:2694)
    at createDropdown (content.js:2707)
    at more_dropdown_init (content.js:2725)
    at async features_run (content.js:2106)
```

```
❌ recently-pushed-branches-enhancements
content.js:2111 TypeError: Cannot read property 'after' of null
    at recently_pushed_branches_enhancements_init (content.js:4990)
    at async features_run (content.js:2106)
```

Any Page

```
❌ deprioritize-marketplace-link
content.js:2111 TypeError: Cannot read property 'closest' of undefined
    at deprioritize_marketplace_link_init (content.js:3607)
    at async features_run (content.js:2106)
```

### LINKED ISSUE #2823: Issue deleted console errors
Githib (finally!) added that when an issue was delete it does not result in a 404 error.
They display an issue deleted page. See https://github.com/sindresorhus/refined-github/issues/2821.

```javascript
content.js:12238 ❌ Refined GitHub: feature `format-discussion-titles`

 TypeError: Cannot read property 'parentElement' of null
    at format_discussion_titles_init (content.js:6309)
    at features_run (content.js:2883)
    at content.js:2938
    at content.js:2830 

	
logError @ content.js:12238
features_run @ content.js:2892
(anonymous) @ content.js:2938
(anonymous) @ content.js:2830
async function (async)
(anonymous) @ content.js:2828
onAjaxedPagesRaw @ content.js:2824
onAjaxedPages @ content.js:2827
add @ content.js:2938
async function (async)
add @ content.js:2909
./source/content.ts @ content.js:6318
__webpack_require__ @ content.js:20
(anonymous) @ content.js:84
(anonymous) @ content.js:87

content.js:12238 ❌ Refined GitHub: feature `clean-sidebar`

 TypeError: Cannot read property 'classList' of null
    at clean (content.js:8342)
    at clean_sidebar_init (content.js:8383)
    at features_run (content.js:2883)
    at content.js:2938
    at content.js:2830 

logError @ content.js:12238
features_run @ content.js:2892
(anonymous) @ content.js:2938
(anonymous) @ content.js:2830
async function (async)
(anonymous) @ content.js:2828
onAjaxedPagesRaw @ content.js:2824
onAjaxedPages @ content.js:2827
add @ content.js:2938
async function (async)
add @ content.js:2909
./source/content.ts @ content.js:8386
__webpack_require__ @ content.js:20
(anonymous) @ content.js:84
(anonymous) @ content.js:87

content.js:12238 ❌ Refined GitHub: feature `sticky-discussion-sidebar`

 TypeError: Cannot read property 'offsetHeight' of null
    at updateStickiness (content.js:4541)
    at sticky_discussion_sidebar_init (content.js:4547)
    at async features_run (content.js:2883) 

logError @ content.js:12238
features_run @ content.js:2892
async function (async)
features_run @ content.js:2883
(anonymous) @ content.js:2938
onAjaxedPagesRaw @ content.js:2824
add @ content.js:2938
async function (async)
add @ content.js:2909
./source/content.ts @ content.js:4554
__webpack_require__ @ content.js:20
(anonymous) @ content.js:84
(anonymous) @ content.js:87

content.js:12238 ❌ Refined GitHub: feature `mark-unread`

 TypeError: Cannot read property 'after' of null
    at addMarkUnreadButton (content.js:4067)
    at mark_unread_init (content.js:4312)
    at async features_run (content.js:2883) 
```

Don't this this will cause any real issues but... ya never know.

Look for this selector should be fine 
```javascript
document.querySelector(".blankslate.blankslate-large.blankslate-spacious")
```

### PR DESCRIPTION
**Pull request by yakov116**
Not sure if this is the best way.

Closes #2823
fixes #2128

### CODE REVIEW

**Comment by yakov116** [comment]
@fregante my issue is that my local node is 12.6 and I can't run ava. I will try tomorrow night or Sunday morning. Feel free to close if you want to take this up.

**Comment by fregante** [comment]
```
npm install -g n
n 11
```

**Comment by yakov116** [comment]
@fregante wouldn't it be better to enforce that each feature must return if the event does not exist?

Like this each feature is responsible for itself?

**Comment by yakov116** [comment]
One more 
`https://github.com/pulls?q=is%3Apr+is%3Aopen+author%3A%40me+archived%3Afalse+sort%3Aupdated-desc` couldnt figure out how fix that one. The user is passed a `pull` since the user detection is from the window.location and the user is not there.

File: source/features/deprioritize-marketplace-link.tsx [hunk 1]
```diff
@@ -24,7 +24,8 @@ features.add({
 	description: 'Moves the "Marketplace" link from the black header bar to the profile dropdown.',
 	screenshot: false,
 	exclude: [
-		features.isGist
+		features.isGist,
+		features.isPasswordPage
```
Comment (fregante) [inline source/features/deprioritize-marketplace-link.tsx]: https://github.com/sindresorhus/refined-github/issues/2128#issuecomment-499903145

No feature works on this page. This check does not belong here, as mentioned in that thread

File: source/features/user-local-time.tsx [hunk 2]
```diff
@@ -101,7 +101,13 @@ function init(): void {
 
 		// Adding the time element might change the height of the hovercard and thus break its positioning
 		const hovercardHeight = hovercard.offsetHeight;
-		select('div.d-flex.mt-3 > div.overflow-hidden.ml-3:not([data-hovercard-type="contributors"]', hovercard)!.append(container);
+
+		const userHovercard = select('div.d-flex.mt-3 > div.overflow-hidden.ml-3', hovercard)!;
+		if (!userHovercard) {
```
Comment (fregante) [inline source/features/user-local-time.tsx]: When does this happen?

File: source/libs/page-detect.ts [hunk 3]
```diff
@@ -103,7 +106,7 @@ export const _isGlobalSearchResults = [
 	'https://github.com/search?q=refined-github&ref=opensearch'
 ];
 
-export const isIssue = (): boolean => /^issues\/\d+/.test(getRepoPath()!);
+export const isIssue = (): boolean => /^issues\/\d+/.test(getRepoPath()!) && document.title !== 'GitHub · Where software is built';
```
Comment (fregante) [inline source/libs/page-detect.ts]: Add a comment explaining what the second part means: why is it there? When does it happen?
```suggestion
export const isIssue = (): boolean => /^issues\/\d+/.test(getRepoPath()!) && document.title !== 'GitHub · Where software is built'; // The title check excludes deleted issues
```

File: source/features/user-local-time.tsx (hunk 2 above)
Comment (yakov116) [reply source/features/user-local-time.tsx]: #2641 
#2549

File: source/features/user-local-time.tsx [hunk 4]
```diff
@@ -101,7 +101,13 @@ function init(): void {
 
 		// Adding the time element might change the height of the hovercard and thus break its positioning
 		const hovercardHeight = hovercard.offsetHeight;
-		select('div.d-flex.mt-3 > div.overflow-hidden.ml-3:not([data-hovercard-type="contributors"]', hovercard)!.append(container);
+
```
Comment (yakov116) [inline source/features/user-local-time.tsx]:
```suggestion
		// Github uses the same class for the contributer hover
```

Should I add a comment?

File: source/features/user-local-time.tsx (hunk 2 above)
Comment (fregante) [reply source/features/user-local-time.tsx]: Didn’t #2641 fix that? We try to avoid these kinds of checks because they make actual errors silent (i.e. when GitHub changes the classes)

Comment (yakov116) [reply source/features/user-local-time.tsx]: Nope

Comment (fregante) [reply source/features/user-local-time.tsx]: This check is too late. Line 86 should be extended to include some check for: "is this hovercard for single user?"

Comment (yakov116) [reply source/features/user-local-time.tsx]: Explain. I was having a hard time with vscode until last night. I will try to see if there is a better later

Comment (fregante) [reply source/features/user-local-time.tsx]: I mean this change should be undone, there’s a lot of code that is run unnecessarily before this. 

It’s better to check whether we need to run this function at all. Line 86 already has checks for this
- is empty? Return
- is timezone element already there? Return

We should add:

- is not a user hover card? Return

Comment (yakov116) [reply source/features/user-local-time.tsx]: Ok lets leave it for now

**Comment by fregante** [comment]
Always good to see some bugs being squashed 🐛
