### PR TITLE
Fix links in `tags-dropdown`

### LINKED ISSUE #3331: `tags-dropdown` doesn't point to tags pages, but to /tree/
1. https://github.com/sindresorhus/refined-github/releases
2. Open the tags dropdown on the top right
3. Nice that the links point to /tree/ pages instead of /releases/tag

This is not working because now tags are lazy-loaded:

https://github.com/sindresorhus/refined-github/blob/120de1b0ebaba019d9775705907c652bbdd770a1/source/features/tags-dropdown.tsx#L20

### PR DESCRIPTION
**Pull request by dertieran**
Fixes #3331

It seems the layout structure changed, so I fixed the selector.
There is also an `id="tags-menu"` on the `[role="tabpanel"]:last-child` element so we could also use that instead.

### CODE REVIEW

**Comment by fregante** [comment]
I can’t check right now but, are we sure that the list has already loaded when this code runs? Maybe it also needs a MutationObserver

**Comment by dertieran** [comment]
It worked for me, but with all the changes in Github lately might be good to confirm this.

But I think the lazy loading was already handled through [`remote-input-success`](https://github.com/github/remote-input-element#events)
https://github.com/sindresorhus/refined-github/blob/75deae9d56cb5ecf7d3045c25b8b6131f2871fc0/source/features/tags-dropdown.tsx#L47-L50

File: source/features/tags-dropdown.tsx [hunk 1]
```diff
@@ -15,7 +15,7 @@ function changeTabToTags(): void {
 
 function updateLinksToTag(): void {
 	// Change links, which point to the content of each tag, to open the tag page instead
-	for (const anchorElement of select.all<HTMLAnchorElement>('.rgh-tags-dropdown .SelectMenu-list:last-child [href*="/tree/"]')) {
+	for (const anchorElement of select.all<HTMLAnchorElement>('.rgh-tags-dropdown [role="tabpanel"]:last-child [href*="/tree/"]')) {
```
Comment (fregante) [inline source/features/tags-dropdown.tsx:18]: The problem was just that `SelectMenu-list` isn't the last child anymore
```suggestion
	for (const anchorElement of select.all<HTMLAnchorElement>('.rgh-tags-dropdown .SelectMenu-list [href*="/tree/"]')) {
```

However we can take this opportunity to make the selector more specific to exclude the branches that also appear in the DOM
```suggestion
	for (const anchorElement of select.all<HTMLAnchorElement>('.rgh-tags-dropdown #tags-menu .SelectMenu-item[href*="/tree/"]')) {
```

Comment (dertieran) [reply source/features/tags-dropdown.tsx:18]: Sure that also works 👍 
I thought the `:last-child` selector was meant to only select the tags tab. 😄
