### PR TITLE
Fix `rgh-feature-descriptions` feature

### LINKED ISSUE #4697: `rgh-feature-descriptions` is broken on `reactions-avatars`
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

```
`rgh-feature-descriptions`: undefined is not an object (evaluating '(await elementReady(".Box-header--blue.Details, include-fragment.commit-loader")).parentElement')
```

### Screenshot

Screen Shot 13
Screen Shot 12

### Console errors

```shell
Not really useful: 👇 


safari-web-extension://DE848C9B-F1EE-494A-9DE4-36164F895DBF/build/refined-github.js:9029:231
asyncFunctionResume@[native code]
[native code]
promiseReactionJobWithoutPromise@[native code]
```

### Example URL

https://github.com/sindresorhus/refined-github/blob/main/source/features/reactions-avatars.tsx

### Browser(s) used

Safari

### PR DESCRIPTION
**Pull request by gamemaker1**
## Related issues

Closes #4697 if merged.

## What this PR does

Changes the CSS selector used to add the feature description box on RGH feature pages from `.Box-header--blue.Details, include-fragment.commit-loader` to `.hx_commit-tease`

## Test URLs

https://github.com/sindresorhus/refined-github/blob/main/source/features/reactions-avatars.tsx
https://github.com/sindresorhus/refined-github/blob/main/source/features/clean-conversation-headers.tsx

### CODE REVIEW

**Comment by kidonng** [comment]
Did you test in Safari? Doesn't seem like a simple selector change can fix it

**Comment by gamemaker1** [comment]
Actually this occurs in Firefox as well:

image

> Did you test in Safari

No, I am on Linux

**Comment by kidonng** [comment]
Yup, you are right, I now see the error on Chrome as well:
image

File: source/features/rgh-feature-descriptions.tsx [hunk 1]
```diff
@@ -94,7 +94,7 @@ async function init(): Promise<void | false> {
 
 	const conversationsUrl = '/sindresorhus/refined-github/issues?q=' + encodeURIComponent(`"${feature.id}" sort:updated-desc`);
 
-	const commitInfoBox = (await elementReady('.Box-header--blue.Details, include-fragment.commit-loader'))!.parentElement!;
+	const commitInfoBox = (await elementReady('.hx_commit-tease'))!.parentElement!;
```
Comment (kidonng) [inline source/features/rgh-feature-descriptions.tsx:97]: You should not replace the entire selector, as `.Box-header--blue.Details` is needed for older versions of GitHub Enterprise and `include-fragment.commit-loader` is needed according to [`2683e30` (#3852)](https://github.com/sindresorhus/refined-github/pull/3852/commits/2683e300976cacbbb71eb219347cb82aa964616b).

```suggestion
	const commitInfoBox = (await elementReady('.Box-header.Details, .Box-header--blue.Details, include-fragment.commit-loader'))!.parentElement!;
```

**Comment by fregante** [comment]
The feature still works on some pages but not others. Make sure that they all still work after this PR:  https://github.com/sindresorhus/refined-github/blob/main/source/features/clean-conversation-headers.tsx


I don't understand why it works only on some pages, what's missing?

File: source/features/rgh-feature-descriptions.tsx (hunk 1 above)
Comment (fregante) [reply source/features/rgh-feature-descriptions.tsx:97]: `rgh-feature-descriptions` does not run on GHE 😃

Comment (gamemaker1) [reply source/features/rgh-feature-descriptions.tsx:97]: Ok, sure

**Comment by gamemaker1** [comment]
Will test on all

File: source/features/rgh-feature-descriptions.tsx (hunk 1 above)
Comment (gamemaker1) [reply source/features/rgh-feature-descriptions.tsx]: > `rgh-feature-descriptions` does not run on GHE smiley

Ohk ... let me know which ones to keep then

**Comment by gamemaker1** [comment]
I thought it might have been because of an update - I didn't see any of the previous selectors when inspecting the HTML

File: source/features/rgh-feature-descriptions.tsx (hunk 1 above)
Comment (kidonng) [reply source/features/rgh-feature-descriptions.tsx]: > [`rgh-feature-descriptions`](/sindresorhus/refined-github/blob/main/source/features/rgh-feature-descriptions.tsx) does not run on GHE 😃

I forgot that 🤣

---

Quoting https://github.com/sindresorhus/refined-github/pull/4559#discussion_r667723258:

> - replace `.Box-header` with `.hx_commit-tease` (it seems to be a unique class name on the relevant pages)

Is there anything prevent us from using `.hx_commit-tease`?

**Comment by gamemaker1** [comment]
Tested it on pretty much all features now (and discovered that firefox does not crash with almost 200 tabs open - yay 😅🎉) - it works! Any other changes to be made?

**Review by fregante — APPROVED** [review]
# 💯
