### PR TITLE
Fix heisenbug in `set-default-repositories-type-to-sources`

### LINKED ISSUE #3908: `set-default-repositories-type-to-sources`: undefined is not an object (evaluating 'link.search')
Screen Shot 1

1. Open a PR like https://github.com/sindresorhus/refined-github/pull/3904
2. Visit the PR Commits tab
3. Open the profile dropdown
	Screen Shot 3

This happens because:
1. `init` is called on every ajax load
2. `init` attaches a mutation handler
3. when the user opens the dropdown, the handler fires twice, but the second time the selector no longer finds anything

### PR DESCRIPTION
**Pull request by cheap-glitch**
Thanks for contributing! 🍄

1. LINKED ISSUES: Fixes #3908

2. TEST URLS: https://github.com/sindresorhus/refined-github/pull/3904 > Go to "Commits" tab > Hover on your avatar

3. SCREENSHOT: -

Changing the selector fixes this, but maybe it's better to check the return value of `select()` instead of applying the modification twice?

### CODE REVIEW

**Comment by fregante** [comment]
It’s best to fix the logic by splitting the init function in 2

File: source/features/set-default-repositories-type-to-sources.tsx [hunk 1]
```diff
@@ -26,7 +26,7 @@ async function init(): Promise<void> {
 
 	// "Your repositories" in header dropdown
 	await onProfileDropdownLoad();
-	addSourceTypeToLink(select('.header-nav-current-user ~ a[href$="tab=repositories"]')!);
+	addSourceTypeToLink(select('.header-nav-current-user ~ a[href*="tab=repositories"]')!);
 }
 
 void features.add(__filebasename, {
```
Comment (fregante) [inline source/features/set-default-repositories-type-to-sources.tsx:32]: I think it would be something like
```suggestion
function profileDropdown () {
	await onProfileDropdownLoad();
	addSourceTypeToLink(select('.header-nav-current-user ~ a[href$="tab=repositories"]')!);		 
}

void features.add(__filebasename, {
 	init: once(profileDropdown)
 }, {
```

File: source/features/set-default-repositories-type-to-sources.tsx [hunk 2]
```diff
@@ -1,4 +1,5 @@
 import select from 'select-dom';
+import once from 'once';
```
Comment (yakov116) [inline source/features/set-default-repositories-type-to-sources.tsx:2]: Look at other features. We use a package oneTime

**Review by fregante — APPROVED** [review]
