### PR TITLE
Restore `bugs-tab` and `releases-tab` title

### LINKED ISSUE #4133: Add tooltips for `bugs-tab` and `releases-tab`
Now that #4108 is implemented, it is time to add tooltips for `bugs-tab` and `releases-tab`, showing the bugs and releases count, just like the issue tab and PR tab. (As I mentioned in https://github.com/sindresorhus/refined-github/issues/3633#issuecomment-706185428 before.)

imageimage

Releases hit 1000: https://github.com/StylishThemes/GitHub-Dark/releases

### PR DESCRIPTION
**Pull request by yakov116**
closes #4133

image

### CODE REVIEW

**Comment by fregante** [comment]
That's a useless tooltip. It only makes sense if the number has been shortened, not always.

**Comment by yakov116** [comment]
Worth the if statement?

File: source/features/bugs-tab.tsx [hunk 1]
```diff
@@ -84,7 +84,6 @@ async function init(): Promise<void | false> {
 	// Set temporary counter
 	const bugsCounter = select('.Counter', bugsTab)!;
 	bugsCounter.textContent = '0';
-	bugsCounter.title = '';
```
Comment (fregante) [inline source/features/bugs-tab.tsx:87]: We still need to reset this as soon as possible because the count is loaded later

File: source/features/bugs-tab.tsx [hunk 2]
```diff
@@ -93,7 +92,9 @@ async function init(): Promise<void | false> {
 
 	// Update bugs count
 	try {
-		bugsCounter.textContent = abbreviateNumber(await countPromise);
+		const bugCount = await countPromise;
+		bugsCounter.textContent = abbreviateNumber(bugCount);
+		bugsCounter.title = String(bugCount);
```
Comment (fregante) [inline source/features/bugs-tab.tsx:97]:
```suggestion
		bugsCounter.title = bugCount > 999 ? String(bugCount) : '';
```

File: source/features/releases-tab.tsx [hunk 3]
```diff
@@ -78,7 +78,7 @@ async function init(): Promise<false | void> {
 			>
 				<TagIcon className="UnderlineNav-octicon"/>
 				<span data-content="Releases">Releases</span>
-				{count && <span className="Counter">{abbreviateNumber(count)}</span>}
+				{count && <span className="Counter" title={String(count)}>{abbreviateNumber(count)}</span>}
```
Comment (fregante) [inline source/features/releases-tab.tsx:81]:
```suggestion
				{count && <span className="Counter" title={count > 999 && String(count)}>{abbreviateNumber(count)}</span>}
```

File: source/features/releases-tab.tsx [hunk 4]
```diff
@@ -118,7 +118,7 @@ async function init(): Promise<false | void> {
 		<a href={buildRepoURL('releases')} className="reponav-item" data-hotkey="g r">
 			<TagIcon/>
 			<span> Releases </span>
-			{count && <span className="Counter">{abbreviateNumber(count)}</span>}
+			{count && <span className="Counter" title={String(count)}>{abbreviateNumber(count)}</span>}
```
Comment (fregante) [inline source/features/releases-tab.tsx:121]:
```suggestion
			{count && <span className="Counter" title={count > 999 && String(count)}>{abbreviateNumber(count)}</span>}
```

**Review by fregante — APPROVED** [review]
Related https://github.com/sindresorhus/refined-github/issues/3633#issuecomment-706208019

😃 

> Worth the if statement?

Good point, but thankfully we can use ternary operators.

Merge after these changes:

File: source/features/bugs-tab.tsx [hunk 5]
```diff
@@ -84,7 +84,6 @@ async function init(): Promise<void | false> {
 	// Set temporary counter
 	const bugsCounter = select('.Counter', bugsTab)!;
 	bugsCounter.textContent = '0';
```
Comment (yakov116) [inline source/features/bugs-tab.tsx:86]:
```suggestion
	bugsCounter.textContent = '0';
	bugsCounter.title = '';
```

**Comment by yakov116** [comment]
> Good point, but thankfully we can use ternary operators.

But typescript does not like ~you~ it 😄

File: source/features/releases-tab.tsx (hunk 4 above)
Comment (fregante) [reply source/features/releases-tab.tsx]: Why not `&&`?
