### PR TITLE
Avoid issue with conflict resolution

### LINKED ISSUE #4673: `resolve-conflicts` may remove unrelated `===================` strings
### Please ensure:

- [X] The bug is caused by Refined GitHub. It doesn't happen if I disable the extension.

### Description

From https://github.com/sindresorhus/refined-github/issues/4672 by @szmarczak

> Sometimes it doesn't work correctly and leads to something like this: [`533e423` (#1118)](https://github.com/apify/apify-js/pull/1118/commits/533e4239cb445a5b8bfaa95001593af887a8013e) (removal of `====================`)

### Screenshot

Screen Shot

### Console errors

_No response_

### Example URL

Any merge conflict page, like https://github.com/sindresorhus/refined-github/pull/148/conflicts

### Browser(s) used

unknown

### PR DESCRIPTION
**Pull request by fregante**
- Fixes #4673

## Test

0. Commit this:

```
Title
====================

Title
====================

Title
====================

Title
====================
```

1. Edit a line in a new branch
2. Edit the same line on `main`
3. Open PR from the branch, in my case https://github.com/fregante/sandbox/pull/29
4. See conflict

## Demo

In this demo I'm highlighting the lines I expect to be deleted. (Selection doesn't affect the behavior)

https://user-images.githubusercontent.com/1402241/130323477-e800493d-5617-4c8d-a2c9-239e639db9cc.mov

## Notes

GitHub’s own editor is confused:

Screen Shot 3

VSCode works correctly:

Screen Shot 4

### CODE REVIEW

File: source/resolve-conflicts.ts [hunk 1]
```diff
@@ -1,8 +1,9 @@
...
-/// <reference types="codemirror" />
+/* eslint-disable unicorn/better-regex -- Go home you're drunk */
 
-// eslint-disable-next-line @typescript-eslint/no-namespace -- TODO: Is any other way supported?
-declare namespace CodeMirror {
+import regexJoin from 'regex-join';
+import type CodeMirror from 'codemirror';
+
+declare module 'codemirror' {
 	interface LineHandle {
```
Comment (fregante) [inline source/resolve-conflicts.ts:7]: Did I just find a way to avoid triple-slash references or was the type package improved to provide this export? Either way… fixed 2 line exception 🎊

**Comment by szmarczak** [comment]
Thanks ❤️
