### PR TITLE
Fix real names not being fetched in Firefox

### LINKED ISSUE #489: Real names aren't shown
I just noticed while reviewing #488 that the real names from #251 aren't even showing up for me. I'm getting the following error:

```
TypeError: /arkon/following is not a valid URL.
Stack trace:
showRealNames/</requests<@resource://gre/modules/ExtensionContent.jsm -> moz-extension://e129e65a-bde7-4a1b-b258-6ae64dd76ba9/content.js:2394:16
showRealNames/<@resource://gre/modules/ExtensionContent.jsm -> moz-extension://e129e65a-bde7-4a1b-b258-6ae64dd76ba9/content.js:2393:20
getCachedUsers/<@resource://gre/modules/ExtensionContent.jsm -> moz-extension://e129e65a-bde7-4a1b-b258-6ae64dd76ba9/content.js:2361:47
```

Perhaps a Firefox issue?

BTW @bfred-it would it be possible to set up source maps?

### PR DESCRIPTION
**Pull request by jgierer12**
Closes #489 

Since Firefox doesn't seem to allow `fetch`ing relative URLs (even though it's in their own [docs](https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API/Using_Fetch)), we now use an absolute URL.

### CODE REVIEW

**Comment by bfred-it** [comment]
That sounds strange, relative URLs should be supported.

**Comment by jgierer12** [comment]
Yes, but it always throws an error with relative URLS.
```
TypeError: /some/relative/url is not a valid URL.
```
As soon as I changed it to an absolute URL, it worked.

**Comment by bfred-it** [comment]
Yeah, it looks like a bug.

File: src/libs/show-names.js [hunk 1]
```diff
@@ -34,7 +34,7 @@ export default () => {
 			}
 		}
 
-		const userUrl = user => `/${user}/following`;
+		const userUrl = user => `${window.location.origin}/${user}/following`;
```
Comment (bfred-it) [inline src/libs/show-names.js]: Can you use `location.origin` here? `location` is global
