### PR TITLE
Fix `hide-empty-meta`

### LINKED ISSUE #2037: Feature `hide-empty-meta` is broken
> I think it's broken as it's supposed to hide this italics text
> 
> Screenshot 2019-05-13 at 23 30 11
>
> Live demo: https://github.com/bfred-it/temp

_Originally posted by @bfred-it in https://github.com/sindresorhus/refined-github/pull/2030/files/5ac58f64b8e7d4479b84acc56b1fe1723ae042e2_

### PR DESCRIPTION
**Pull request by notlmn**
Fixes #2037

# Test

https://github.com/Witold101/wpw

### CODE REVIEW

File: source/features/hide-empty-meta.tsx [hunk 1]
```diff
@@ -2,8 +2,10 @@ import select from 'select-dom';
 import features from '../libs/features';
 
 function init(): void {
-	if (select.exists('.repository-meta em') && !select.exists('.js-edit-repo-meta-button')) {
-		select('.repository-meta')!.style.display = 'none';
+	const emptyDescription = select('.repository-content > :not(#readme):not(.commit-tease) em');
```
Comment (bfred-it) [inline source/features/hide-empty-meta.tsx]: There are a lot of other children in `.repository-content`, we can't go by exclusion

Screenshot 2019-05-14 at 00 22 06

It should probably start with `#repo-meta-edit` or maybe just be `#repo-meta-edit em`. Double-check

Comment (yakov116) [reply source/features/hide-empty-meta.tsx]: I also think the selector is different if you have rights to edit

Comment (notlmn) [reply source/features/hide-empty-meta.tsx]: > There are a lot of other children in `.repository-content`, we can't go by exclusion

But usually commit list an the the readme are the only likely ones to contain an `em`.

-----------------

> It should probably start with `#repo-meta-edit` or maybe just be `#repo-meta-edit em`. Double-check

Targeting `#repo-meta-edit em` fails for repos with no permissions, the existence of `#repo-meta-edit` is the condition to bail.

Comment (notlmn) [reply source/features/hide-empty-meta.tsx]: > I also think the selector is different if you have rights to edit

`#repo-meta-edit` only exists if you have permission, else its just `em` inside a "`div`-tree-with-utility-class" hell.

Comment (bfred-it) [reply source/features/hide-empty-meta.tsx]: True, actually because it's so high in the dom we might get away with just `.repository-content em` because `select` only gets the first one

Comment (bfred-it) [reply source/features/hide-empty-meta.tsx]: Screenshot 2019-05-14 at 00 38 15

Yeah it's definitely the first one

Comment (bfred-it) [reply source/features/hide-empty-meta.tsx]: But it should drop `d-flex`, not just em, otherwise there's some space left behind
