### PR TITLE
Fix `highest-rated-comment` overlap with avatar

### LINKED ISSUE #3338: `highest-rated-comment` overlap with avatar
Happens on https://github.com/ysc3839/FontMod/issues/59:
image

### PR DESCRIPTION
**Pull request by yakov116**
Fixes #3338 

Test on https://github.com/ysc3839/FontMod/issues/59

### CODE REVIEW

File: source/features/highest-rated-comment.tsx [hunk 1]
```diff
@@ -76,6 +76,8 @@ function linkBestComment(bestComment: HTMLElement): void {
 
 		// Copy avatar but link it to the comment
 		const avatar = select('.TimelineItem-avatar', bestComment)!.cloneNode(true);
+		// Remove the check icon from the preview #3338
+		select('.octicon-check.text-green', avatar)!.remove();
```
Comment (fregante) [inline source/features/highest-rated-comment.tsx:80]: This is in the middle of the “ Copy avatar but link it to the comment” operation. Move it 4 lines down, with an extra line
